.github/workflows/ci.yml
There is a bug with `py-spy --gil` and python 3.8.8:
https://github.com/benfred/py-spy/issues/357
Changing the version in CI to avoid it until it is fixed
=> Change python version to 3.8.5 in CI

gprofiler/merge.py
By turning the <comm> to non-greedy, it would not contain the whitespace that comes after it.
The whitespace is of different length depending on how many digits the pid is so we get stacks
that are "the same" but are not merged because the process name differs
We are seeing flamegraphs where stacks from the same process are not merged, see image below
I looked at collapsed files before the change and after it, the bug is clearly fixed
All existing tests pass
=> Remove whitespace after process names

build.sh
We released a new version of [perf](https://github.com/Granulate/linux/releases/tag/v5.6g2-perf), updating `build.sh` to download it
This perf update will mean that the root stack is the process name instead of the thread name, which is much clearer
=> Update perf to a newer release

gprofiler/java.py, gprofiler/python.py, gprofiler/utils.py, tests/conftest.py, tests/containers/python/Dockerfile, tests/containers/python/fibonacci.py
This is more accurate than "pgrep python", because a Python script exec'd directly won't
have "python" in its comm (hence the different PYTHON_KNOWN_PROCS we pgrep'd for).
This new approach is more accurate, and it can be taken to further to actually finding
processes with ".*python.*" in their /proc/pid/maps file.
Catch more processes we used to miss.
By running the existing tests + I'll add a test for a Python script with a shebang.
=> python: Select processes to profile based on "python*" in their exe's basename

.dockerignore, Dockerfile, build.sh
I noticed that some untracked files were copied into the image. Additionally, `__pycache__` and some `*.pyc`s.
This PR copies files more strictly. It's not perfect yet - perfect would be https://stackoverflow.com/q/51693245, or otherwise to maintain the full list of desired files in `.dockerignore`, which isn't worth the hassle, IMO.
Prevent unwanted files from reaching the image.
I built the image, then verified the profiler manages to run and all its needed files are found.
=> Improve Dockerfile ignored files

gprofiler/java.py, gprofiler/main.py, gprofiler/merge.py, gprofiler/perf.py, gprofiler/python.py, tests/conftest.py, tests/test_sanity.py
Preliminary support for defining a profiler which outputs stack-collapsed records in a format different from py-spy and async-profiler.
Move parsing logic from `main` to each profiler so additional profilers can implement parsing for their own formats.
Current architecture requires all runtime profilers to dump samples in a file in a fixed stack-collapsed format. This PR relaxes this requirement to allow for compatibility with other profilers that output samples in their own custom formats. This allows integrating other profilers more cleanly and easily.
This is a purely architectural change, so relying only on CI tests.
N/A
=> Support other profiler output formats

.github/workflows/ci.yml, build.sh, gprofiler/python.py
Upgrade py-spy to its latest release. Also, reverted the change from https://github.com/Granulate/gprofiler/pull/4.
Latest release handles more CPython versions, and exposes the `--full-filenames` flag which is useful for system-wide profiling.
I have run the profiler locally and saw that Python stacks now have full filenames. Additionally, I have run the tests.
=> python: Upgrade py-spy

gprofiler/python.py, gprofiler/utils.py, tests/containers/python/Dockerfile.libpython, tests/test_python.py, tests/test_sanity.py
In 3e9381bc4ff7 I suggested this change as an improvement, but it's actually required
because we currently miss executables which load libpython, such as uwsgi.
This change means that we'll prefer the Python samples from *any* process which has
libpython loaded, even if it doesn't even run Python code now. We might need to address
that later, by making smarter decisions on the source for our samples.
Fixes: 3e9381bc4ff7
To enable profiling of processes whose basename isn't `python`, such as `uwsgi`.
1. By running `uwsgi` on my box and seeing it "get caught" in the profiler.
2. By the new test `test_python_select_by_libpython`.
=> python: Select processes to profile based on python/libpython in their maps

gprofiler/main.py, gprofiler/resources/flamegraph/flamegraph_template.html
Fixes timestamp formatting in generated flamegraphs.
See screenshots.
I ran the profiler locally and verified that timestamps are now being formatted in correctly.
Was:
Now:
=> Fix timestamp formatting into the generated flamegraph

.flake8, gprofiler/utils.py, lint.sh, tests/conftest.py, tests/test_python.py
Provide a faster implementation of `pgrep_maps` from https://github.com/Granulate/gprofiler/pull/9.
According to the tests I conducted in that PR, the old `pgrep_maps` wasn't the core issue in gprofiler. However, as the benchmarks here show, it is very slow (compared to what we could get):
```
root@0728b99acd88:/# cat bench.py 
from __future__ import annotations
import subprocess
import sys
from psutil import Process
import re
import psutil
if sys.argv[1] == "new":
def pgrep_maps(match: str) -> List[Process]:
result = subprocess.run(
f"grep -lE '{match}' /proc/*/maps", stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, shell=True, text=True
)
assert result.returncode in (0, 2)
processes: List[Process] = []
for line in result.stdout.splitlines():
assert line.startswith("/proc/") and …
```
=> utils: Provide a more performant implementation of pgrep_maps()

build.sh
This reverts commit cfa8d59928a32fb653d37ac00925bbfd5b4e3741.
This new release has caused some unwanted side effects on old kernels - we've
used the incorrect "comm" for certain threads.
We suspect it's related to `PERF_RECORD_MISC_COMM_EXEC` not being available in <3.16 (see https://github.com/Granulate/linux/pull/1/commits/8c3e6c8aff99a6d341eeea41abe67eab92f6a417 for the change we are reverting here)
Fixes `perf` stacks in old kernels.
We merely revert to the old version, which was tested.
=> Revert "Update perf to a newer release (#3)"

build.sh, gprofiler/java.py, gprofiler/main.py, gprofiler/utils.py, tests/conftest.py
This PR improves the robustness of the Java profiler.
* Upgrade to async-profiler v2.0
* Use async-profiler's log option to capture errors & warnings, and print them on profiling failure.
* If load fails, check if libasyncProfiler.so was loaded to the target process, and log it accordingly.
* Handle absolute symlinks in other namespaces (resolve part by part in usermode, so it works over /proc/pid/root)
* Use separate temporary directories per profiled process, to avoid possible races when copying libasyncProfiler.so
and when removing the directories after profiling is done (if the same directory is used by multiple profile_process threads).
* tests: Run Java container as non-root - ensures we give correct permissions to output paths, etc.
Improve the robustness of the Java profiler.
* …
=> java: Improve profiler robustness

gprofiler/perf.py
Avoid cluttering other parts of the filesystem (by default, it uses /root/.debug).
When gprofiler runs as a container, it doesn't really matter (both /root/ and /tmp
are just part of the container filesystem).
But we plan to allow running gprofiler as an executable, and in that case, we
should keep our files in /tmp/gprofiler.
Keep our files in `/tmp/gprofiler`.
I ran the gprofiler container with this fix and verified that `/root/.debug` is not used anymore, and that all cached DSOs go to `/tmp/gprofiler/...`.
-
=> perf: Use /tmp/gprofiler/perf-buildids as the buildid cache for perf

build.sh
Update `burn` binary to "burn v1.0.1(g2)" - statically linked.
Use statically linked burn as part of used binaries to support systems without the need for all native DSO.
- Successfully built gProfiler docker image.
- Ran the docker image and validated the new `burn` works properly and produces the same flamegraphs.
=> flamegraph: burn: use statically linked burn v1.0.1(g2)

tests/__init__.py, tests/conftest.py, tests/test_python.py, tests/test_sanity.py
The `profiler` fixture assumes only a single profiler implementation for a
particular runtime. This change inlines it and requires unit tests to be
written for a particular implementation. The existing test for the gprofiler
docker image remains the same. In addition, we now no longer execute test
applications of runtimes that are not being tested, and we don't execute an
application both within a container and on the host for the same test
permutation.
After this change, it is easier to write tests for a particular profiler
implementation, or for a particular application runtime.
CI.
=> tests: More fine-grained testing for specific runtimes or profilers.

gprofiler/java.py
We'll allow deploying gprofiler as a standalone executable; in that case, its files
will be extracted to the filesystem by another component (e.g: pyinstaller) and may have
improper permissions, so we can't rely on them when copying. This ensures the permissions
are okay.
Preparation for executable deployment.
Our tests.
=> java: Explicitly chmod() libasyncProfiler.so in its target directory

README.md, gprofiler/exceptions.py, gprofiler/java.py, gprofiler/utils.py
Check whether `nsenter` is installed or not, and raise a descriptive error if not.
Makes it more more clear that you need to install `nsenter`, when compared to `FileNotFoundError: [Errno 2] No such file or directory: 'nsenter'`.
Ran the container normally - it works fine & profiles Java, because `nsenter` exists.
Then I added some logic to remove `/usr/bin/nsenter` and I got the nice exception.
=> Check for availability of "nsenter" before attempting to use it

gprofiler/utils.py
run_process() only logged the command upon entry. If multiple commands are
executed concurrently, it's hard to correlate the exit codes / outputs with
the command that generated them.
Make it easier to read the logs.
Manually.
=> utils: Include command in run_process() logs

gprofiler/main.py, gprofiler/utils.py
If Java profiling fails, it should fail the Python one. Same goes the other way.
Do not unnecessarily fail the run.
1. CI
2. I manually injected errors into the Python profiler and verified that I get the log `gprofiler: python profiling failed`, while gprofiler continues.
=> Log and continue on runtime profiler errors

gprofiler/utils.py, tests/test_executable.py
This fixes 2 points:
1. When passing `encoding=...`, Python tries to load the encoding file (a part of the standard library) if it's not loaded yet. See `_PyCodec_Lookup`. We've already changed the mount namespace so the files are not available anymore. It worked for me before because my host box is Ubuntu 20.04 (same as the container image :sweat_smile: ). After this fix, the function runs successfully on RHEL.
2. Parsing of another variant of glibc version string.
Get `get_libc_version()` working on more OSes.
Manually on an AmazonLinux2 machine. And again on my Ubuntu.
=> utils: Fix get_libc_version() on RHEL

.github/workflows/build.yml, cmp_tags.sh
CI was [failed](https://github.com/Granulate/gprofiler/runs/2336547782?check_suite_focus=true) while running `cmp_tags` script. I think the reason is that the checkout step is fetch only a single commit by default.
I added an option of `fetch-depth: 0` to checkout step, which should fetch the whole history and tags.
`git fetch origin` command was removed from `cmp_tags` script 
Make the CI work
Push test tag in different branch and test that this step is passed
=> CI error while running cmp_tags.sh fix

.github/workflows/ci.yml
Since python version 3.8.9 released (02/04/21), the CI was failed on python profiling tests.
The reason is that `py-spy` v0.3.5 doesn't support that version.
After `py-spy` will added need to set the latest version.
Make the CI pass
Run CI after fixes
=> Python version in pytest CI changed to absolute 3.8.8

README.md, gprofiler/main.py
It's confusing that the interval is in minutes and duration in seconds.
Also, it makes sense to allow finer control over the interval - that is, seconds and not minutes.
Removes confusion + allows for finer control on interval.
Locally.
=> Change --profiling-interval units to seconds

gprofiler/utils.py
Will be useful when debugging.
Helps debugging Python-related issues in gProfiler - since gProfiler may run on several versions, depending on the run type.
Manually:
```
[2021-04-27 09:30:38,514] INFO: gprofiler.utils: gProfiler Python version: 3.8.5 (default, Jan 27 2021, 15:41:15) 
```
=> Log the Python version gProfiler runs with

gprofiler/main.py
When executed as a regular user, opening the default log file will fail. Check for root privileges first.
=> Check for root privileges before attempting to open /var/log/gprofiler/gprofiler.log

gprofiler/python.py, pyi.Dockerfile, scripts/list_needed_libs.sh
A bunch of commits that'll make it more robust.
1. Install UPX so PyInstaller uses it and the size goes down a bit.
2. Fail PyInstaller build if any of our `gprofiler.*` 
3. Avoid `COPY . .` so build is cached for non-code changes.
4. Include DSOs needed by our resources when calling staticx. This step also ensures all DSO dependencies are resolved, and fails the build if they are not. Currently all executables are static, only PyPerf is dynamic ~~and misses some DSOs in `centos:7`, so build fails.~~
~~I plan to add a few more commits of improvements here (stuff for staticx as well)~~
Easier development & less chances to inject errors.
Locally.
I tried to build with `SyntaxError`s and now the build fails (instead of passing, and producing a broken binary which results in `ImportError`) - …
=> PyInstaller: Improvements & robustness

gprofiler/exceptions.py, gprofiler/main.py, gprofiler/python.py, gprofiler/utils.py, tests/test_libpython.py, tests/test_sanity.py
I see no reason to run the PyPerf bootstrap checks again right after running `PythonEbpfProfiler.test`. It only slows down the boostrap of gProfiler.
I added timeouts in `_dump()` (called every `snapshot()`) so we can catch dead/hanging PyPerfs.
Faster bootstrap of gProfiler.
Manually.
=> python: PyPerf: Faster initialization + timeouts in snapshot()

Dockerfile, pyi.Dockerfile
Upgrade PyPerf to include https://github.com/Granulate/bcc/pull/2 and fix `git clone` for the reason described in https://github.com/Granulate/gprofiler/pull/54#issuecomment-830710450.
As mentioned in the last commit - I like the "git reset --hard <sha>" because it's the best way to hardcode revisions,
so I prefer to keep it (although it's the source for this problem... on the other hand, it helped us to avoid "implicitly" upgrading PyPerf, which is not desired).
Upgrade PyPerf with recent fix.
Tested the new gProfiler w/ the new PyPerf locally.
=> python: Upgrade PyPerf

gprofiler/utils.py
If executable gProfiler is run from `/tmp`, there is a collision with TEMPORARY_STORAGE_PATH.
By default the executable name is `gprofiler` as well the temp directory is `gprofiler`
Make possible to run gProfiler from `/tmp` with default names.
Compiled locally and ran on Ubuntu 18.04 VM under `/tmp` dir.
Previous version printed `NotADirectoryError: [Errno 20] Not a directory: '/tmp/gprofiler/tmpssruylt3'`
Version with the change worked as expected.
=> Run gProfiler from /tmp dir bug

gprofiler/main.py
After https://github.com/Granulate/gprofiler/pull/42 and https://github.com/Granulate/gprofiler/pull/45. Based on https://github.com/Granulate/gprofiler/pull/45, will rebase after it's merged.
When run under staticx & PyInstaller, both of them forward (some of the) signals
to the gProfiler. Effectively, for a single ^C on my terminal, gProfiler gets 3
signals, as can be seen by "perf record -e signals:signal_deliver":
gprofiler 908113 [007] 241166.780316: signal:signal_deliver: sig=2 errno=0 code=128 sa_handler=7f6804a00120 sa_flags=4000000
gprofiler 908112 [004] 241166.780356: signal:signal_deliver: sig=2 errno=0 code=128 sa_handler=404470 sa_flags=14000000
gprofiler 908101 [010] 241166.780356: signal:signal_deliver: sig=2 errno=0 code=128 sa_handler=400bfd sa_flags=4000000
gprofiler …
=> Ratelimit KeyboardInterrupts to avoid double/triple signalling

.github/workflows/build.yml, README.md, gprofiler/java.py, gprofiler/utils.py
Use new `run_in_ns()` helper instead of using `nsenter` to implement the JDK version checking.
Based on https://github.com/Granulate/gprofiler/pull/52 for some of the changes. Will merge after it.
Drop dependency on `nsenter`.
Checked that we correctly get the JDK version for the `java` image (Debian 8 based) and `java:alpine` (Alpine based.. duh :)
=> java: Use run_in_ns() instead of nsenter for JDK version check

Dockerfile, dev-requirements.txt, exe-requirements.txt, pyi.Dockerfile, scripts/build.sh, scripts/pyspy_build.sh, scripts/pyspy_env.sh, tests/test_libpython.py, tests/test_sanity.py, tests/utils.py
~~Based on https://github.com/Granulate/gprofiler/pull/67.~~
Upgrade py-spy to its latest release, and include the build logic here (instead of downloading from GH releases) so it's easier to make changes in py-spy and rebuild gProfiler with them.
Regarding adding the build of py-spy here - it's easier for new developers to work on this project if the build is self contained and it's clear from where each resource comes, and how to reproduce that resource.
Our tests.
=> python: Add py-spy build logic, and upgrade it

gprofiler/utils.py
In 4201d640f15136314d42dbcb926dbde0c67e12ef I changed pgrep_maps() to use run_process().
It was using subprocess.run() without check=True, thus it wasn't expecting an exception to
be raised if the command exits with non-0.
Fix the bug.
I ran it and now I see lines like: `[2021-05-13 18:33:49,775] DEBUG: gprofiler.utils: (["grep -lP '(?:^.+/(?:lib)?python[^/]*$)|(?:^.+/site-packages/.+?$)|(?:^.+/dist-packages/.+?$)' /proc/*/maps"]) exit code: 2`, and gProfiler continues running (and profiles existing Python processes as expected)
=> utils: Add "check" parameter to run_process()

gprofiler/python.py
Since a3b5b73949bc6f064c15e3966cfbb25ce208e497 we're matching on processes with {site,dist}-packages
in their maps (aiming at CPython native extensions).
This matches on native extensions loaded into other Python implementations, such as PyPy.
However, py-spy can't profile them. So we'll avoid trying to profile them (to avoid the possibly-obscure
error message from py-spy). We can add more ignored implementations later, if we encounter any.
Example error:
```
[2021-05-13 18:45:13,061] INFO: gprofiler.python: Profiling process 671516 (['pypy'])
....
[2021-05-13 18:45:13,149] DEBUG: gprofiler.utils: (['/app/gprofiler/resources/python/py-spy', 'record', '-r', '10', '-d', '60', '--nonblocking', '--format', 'raw', '-F', '--gil', '--output', '/tmp/gprofiler_tmp/tmpvi62nyce/671516.py.col.dat', …
```
=> python: py-spy: Ignore PyPy

.dockerignore, Dockerfile, pyi.Dockerfile, scripts/build.sh
1. Pin Docker image versions (see 1st commit message for details)
2. Improve `.dockerignore` (see 2nd commit message). Fixes local builds in case you had files in `gprofiler/resources`....
3. Avoid annoying `curl` warning
Improve build.
Our tests.
=> build: Pin image versions, improve .dockerignore and more

Dockerfile, README.md, gprofiler/main.py, gprofiler/php.py, gprofiler/python.py, gprofiler/utils.py, pyi.Dockerfile, scripts/phpspy_build.sh, tests/__init__.py, tests/conftest.py, tests/containers/php/Dockerfile, tests/containers/php/fibonacci.php, tests/test.sh, tests/test_executable.py, tests/test_sanity.py
Add initial support for PHP processes profiling using phpspy project (Granulate's fork) in continuous mode (pgrep mode in phpspy)
Like Java and Python, we would like to support PHP runtime profiling.
At this point only PHP workloads running on top of [php-fpm](https://www.php.net/manual/en/install.fpm.php), in the future adding support to PHP running inside apache workers [`mod_php`](https://cwiki.apache.org/confluence/display/HTTPD/PHP) and other options.
* Based on Granulate's fork release  [Granulate phpspy v0.6.0-g3](https://github.com/Granulate/phpspy/releases/tag/v0.6.0-g3)
* Automatic tests have been written for both container and executable packaging methods. 
* Granulate phpspy fork was tested manually.
Drupal (running inside a container on the same host as the gProfiler): 
* …
=> Initial PHP support using phpspy

gprofiler/java.py, gprofiler/utils.py
This has the benefit of working even after the binary was deleted. This is aiming for the "replaced" case - the Java package being auto-upgraded, for example. If the Java package was removed, then we can still run `java` this way, but all libraries will be missing.
Without this change, we `readlink` the file which was replaced, thus the `readlink` returns `.... (deleted)` and that file can't be executed, ofc.
We could also just strip the `(deleted)` part but I like this solution more. It is more accurate.
As noted in the comment in `_get_java_version()`, this grew too complex IMO and I want to simplify this check. In a future PR....
Allow profiling Java processes which run a `java` been that's been replaced on disk.
First terminal:
```
root@b4cf39dc87a0:/# java Target
```
runs forever... …
=> java: Execute "java" in the JDK version check via /proc/pid/exe

deploy/k8s/gprofiler.yaml
Fixes an indentation error in the k8s YAML.
Fix an error.
Tested the fixed YAML on my cluster.
=> deploy: k8s: Fix indentation errors in YAML

README.md, gprofiler/main.py, gprofiler/merge.py, gprofiler/utils.py
Need to get the hostname in init UTS NS, otherwise we might be seeing the container / Pod name.
Get the correct hostname in containerized applications. Currently we instruct people to run gProfiler with `--network=host` for no good reason. I will remove it. Also, our k8s YAML doesn't have `hostNetwork: true`.
I added a print for `socket.gethostname()` w/o escaping the UTS NS. It prints the container hostname. This code prints the real hostname.
=> Get hostname from host UTS NS and log it

gprofiler/client.py, gprofiler/main.py, gprofiler/merge.py, gprofiler/utils.py
Based on https://github.com/Granulate/gprofiler/pull/98.
This PR lets gProfiler send a bunch of useful parameters in the query string of its requests. This is done merely for logging purposes - we don't extract these values in our backend; our ALB is able to extract parameters from the query string, and we can use these for proper logging & monitoring of sent requests.
Help us debug & track requests to the backend, by logging useful pieces of data by our ALB.
I ran this version and was able to view all data correctly in the ALB logs.
Athena query sample:
=> Include parameters in POST query string for requests logging

scripts/perf_env.sh
The build installs `texlive-*-doc` packages which amount to 500MB+ download. For example, `texlive-latex-extra-doc`:
```
Get:359 http://archive.ubuntu.com/ubuntu xenial/main amd64 texlive-latex-extra-doc all 2015.20160320-1 [338 MB]
```
On a slow/metered connection this is a considerable barrier to building the image. We don't need these packages.
Build succeeds, perf still works. I don't think perf requires any of the recommended packages besides what's already specified.
=> Don't install unneeded packages when building perf

tests/conftest.py
When the app container exits during tests we get a hang. This raises an exception with the logs instead.
=> Raise error instead of infinitely looping when app container exits prematurely

Dockerfile
Started with dive (https://github.com/wagoodman/dive) but eventually there were
2 simple actions that drastically increased the size, so I avoided them:
1. Installing too many packages due to recommendation
2. Generation of egg files & copying the resources to multiple directories
This is without squashing. --squash currently reduces only 1 MB, because we don't
remove anything in any layer. If we do get to do that, we can add squashing.
Size can be decreased even further, 328 MB is not the lowest we can get to.
Next steps should be trying alpine, IMO.
Shrink our Docker image, so running gProfiler requires less disk space.
CI
=> Shrink Docker image size: 789 MB -> 328 MB

gprofiler/utils.py, tests/test_executable.py, tests/test_java.py, tests/test_sanity.py, tests/utils.py
Handle grep's "not found" error in `pgrep_maps()`. We haven't encountered it by now, because `pgrep_maps()` was run only on Pythons, and we always have Pythons running.
Get rid of this error in the logs:
````
[2021-06-12 10:22:28,386] DEBUG: gprofiler.utils: (["grep -lP '(?:^.+/ruby[^/]*$)' /proc/*/maps"]) exit code: 1
[2021-06-12 10:22:28,386] ERROR: gprofiler: ruby profiling failed
File "/app/gprofiler/main.py", line 271, in _snapshot
process_perfs.update(future.result())
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
return self.__get_result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
raise self._exception
File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = …
```
=> Handle grep's "not found" error in pgrep_maps()

gprofiler/client.py
Adds gProfiler version to the query params URL; see https://github.com/Granulate/gprofiler/pull/99.
See https://github.com/Granulate/gprofiler/pull/99.
Built & ran gProfiler - verified the new `version` field shows correctly in Athena.
=> Add version to query params

README.md, gprofiler/main.py, gprofiler/python.py, tests/test_libpython.py
~~Based on https://github.com/Granulate/gprofiler/pull/108 and https://github.com/Granulate/gprofiler/pull/89, review only after.~~
Adds the `--python-mode` option:
* `auto` - try PyPerf, fallback to py-spy
* `pyperf` - PyPerf, and no fallback
* `pyspy` - py-spy w/o trying PyPerf
* `none` - like `--no-python`.
Give tighter control over which profilers are run, exactly. It's possible to want to use PyPerf with no fallback, or to avoid trying PyPerf to begin with.
* Running with `auto` - PyPerf is selected, if I "hide" kernel headers then py-spy is selected
* Running with `auto` and killing PyPerf - `Python eBPF profiler failed (exit code: -15), falling back to py-spy`
* Running with `pyperf` and no kernel headers - no Python profiler is used
* Running with `pyperf` and PyPerf is killed - …
=> python: Add --python-mode option

gprofiler/merge.py
I've accidentally swapped the condition in #89.
Usually the ratio is close to 1, and anyway the process stacks won't amount to more
than the perf stacks in a normal situation, so it doesn't mess with the results
too much.
Fix a bug
```
diff --git a/gprofiler/python.py b/gprofiler/python.py
index b53a2db..095eab3 100644
--- a/gprofiler/python.py
+++ b/gprofiler/python.py
@@ -40,7 +40,7 @@ class PySpyProfiler(ProfilerBase):
resource_path("python/py-spy"),
"record",
"-r",
-            str(self._frequency),
+            str(1),
"-d",
str(self._duration),
"--nonblocking",
(END)
```
With this patch on master, gProfiler runs with `-d 5` and default frequency, I run Python with `while 1: pass` and I get 0 stacks (because the division is incorrect so it's scaled to 0 samples).
With this patch on …
=> Fix incorrect scaling in merge_profiles()

gprofiler/utils.py
Avoid leaking fds :(
Avoid leaking fds.
CI.
Verified fds are not leaked anymore, e.g `lr-x------ 1 root root 64 Jun 24 19:40 6 -> 'mnt:[4026531840]'` and `lr-x------ 1 root root 64 Jun 24 19:40 3 -> 'net:[4026532008]'`.
Also verified the output looks good (i.e, move to namespaces still happens correctly)
=> utils: Don't leak NS fds in run_in_ns()

gprofiler/python.py, gprofiler/utils.py
Makes it possible to get more information about what happened by reading the exception
message.
I didn't add it for obvious cases (e.g: assert x is not None).
Also didn't add it for tests code, because pytest adds its introspection.
See description ^^
CI
=> Add assert failure messages where missing

tests/test_java.py
Currently, tests are having an annoying PyTest warning because PyTest tries to collect `TestsAsyncProfiledProcess` but fails because the `__init__` of this class is implemented and PyTest thinks this a "class" test and tries to collect it during the PyTest collection phase.
Unfortunately, there is no built-in decorator in PyTest that avoids collecting selected test items, so simply just rename the class name to avoid collection.
Tested by the CI
=> Rename tests util class name to avoid PyTest collection

gprofiler/ruby.py
Runs rbspy in silent mode, to avoid unwanted output that only clutters the gProfiler logs (since it gets logged in verbose mode). I noticed it in the tests, actually: https://github.com/Granulate/gprofiler/pull/128/checks?check_run_id=2947056638
Remove garbage from our logs.
Ran gProfiler w/o this commit - saw lots of outputs like:
```
[2021-06-29 23:11:33,721] DEBUG: gprofiler.utils: (['/app/gprofiler/resources/ruby/rbspy', 'record', '-s', '-r', '11', '-d', '5', '--nonblocking', '--on-cpu', '--format=collapsed', '--file', '/tmp/gprofiler_tmp/tmpnz5h2fnb/rbspy.FMyipkFJlKBCCPcq.198335.col', '--raw-file', '/dev/null', '-p', '198335']) stdout: b'\x1b[2J\n\x1b[0;0H\n% self  % total  name\n100.00   100.00  <main> - (irb)\n  0.00   100.00  start - /usr/local/lib/ruby/3.0.0/irb.rb\n  0.00 …
```
=> ruby: Run rbspy in silent mode

gprofiler/merge.py, gprofiler/python.py, gprofiler/ruby.py, tests/test_executable.py
We do not delete the output files of py-spy and rbspy. This PR fixes that.
The issue was introduced in 1efe4a7f87d322beaa1708cb56a5913c18e316e9 (version 1.0.0) - we ceased from deleting the core temporary folder each iteration, instead it survives for the lifetime of the `GProfiler` object.
It was worsened by 0ab54a089f9c31d267b29e4a1b33060c68ff7e58 which added random a prefix in each output file - so now files of the same target PID don't override each other; so storage keeps on growing!
Bugfix.
1. Verified manually that files are now gone.
2. Added logic to the tests to ensure it from now on.
=> python, ruby: Remove collapsed files after reading

gprofiler/utils.py
Seen this racy error in the CI. Apparently it's a valid return value from the kernel for this `read`.
Avoid logging ERRORs on non-error stuff.
CI
=> utils: pgrep_maps(): Ignore "No such process" errors

.github/workflows/build.yml
Latest release 1.1.5 was done w/o bumping `__version__` (my :dumb:), adding this to avoid such cases in the future.
Avoid making human errors when releasing a version.
Tested this snippet locally on my shell. Fails if the tag doesn't match.
=> ci: Reject non-matching version between git tag and code

gprofiler/java.py, gprofiler/profiler_base.py, gprofiler/python.py, gprofiler/ruby.py, gprofiler/utils.py
Started with logging NoSuchProcess exceptions from profilers as DEBUG, not ERROR.
Then created `ProcessProfilerBase` to reduce code dup, it was time...
Reduce the error logs & reduce code dup.
CI
=> Create ProcessProfilerBase and treat NoSuchProcess as DEBUG

tests/containers/ruby/Dockerfile
2.6.8 was released and rbspy doesn't support it yet, so tests fails.
=> tests: ruby: Pin version to 2.6.7

gprofiler/java.py, scripts/async_profiler_build.sh
By embedding the gProfiler version in AP dir, we will have different dirs for different gProfiler
releases.
**Note:** This breaks the "AP stop" logic across gProfiler versions: if I run version X, kill it brutally, then run version Y, the new AP will be loaded as a different DSO (since it has a different path) and it may cause harm (see https://github.com/jvm-profiling-tools/async-profiler/issues/395 for example). Need to think on a workaround / a different approach for allowing AP upgrades. Opening this PR for discussion.
Allow different gProfiler versions to use different APs. So if we upgrade the AP version in a future gProfiler release, and gProfiler is upgraded on a box which already ran an old version, it will use the new binary.
=> java: Allow different gProfiler versions to use different APs

gprofiler/main.py, gprofiler/utils.py
Add `--log-cpu-usage` which prints the CPU usage (as measured by cgroups) of each profiling session, and also when gProfiler exits.
To allow us to measure optimizations & check for regressions.
Ran it locally and verified the numbers make sense. Also ran `yes > /dev/null` alongside in the container, and this pumps the reported value.
=> Log CPU usage

scripts/phpspy_build.sh
Includes this commit: https://github.com/Granulate/phpspy/commit/af1d74ebd4f9c27486e82397eafde1c450f06510 which fixes an annoying bug :(
```
[2021-07-20 12:46:22,529] DEBUG: gprofiler.php: phpspy: error: objdump: /proc/1649256/root//app/gprofiler/resources/php/phpspy: not a dynamic object
[2021-07-20 12:46:22,530] DEBUG: gprofiler.php: phpspy: error: get_symbol_offset: Failed
[2021-07-20 12:46:22,530] DEBUG: gprofiler.php: phpspy: error: error: pgrep mode: main_pid routine returned non ok status and PID (1649256) is not dead, rv = 1, errno - 0
[2021-07-20 12:46:22,530] DEBUG: gprofiler.php: phpspy: error: sh: 1: Syntax error: Unterminated quoted string
[2021-07-20 12:46:22,530] DEBUG: gprofiler.php: phpspy: error: try_get_php_version: Could not detect PHP version
[2021-07-20 12:46:22,530] …
```
=> Upgrade phpspy

README.md, gprofiler/client.py, gprofiler/main.py, gprofiler/merge.py
Because the legacy V1 profile upload method is still useful in some scenarios, I've added the option to use a new gProfiler with the legacy endpoint. 
I've added the new `--legacy-profile-api-version` option, which currently supports the `V1` value. If this option is enabled, then the gProfiler will not get the container names of stacks and each line in the profile content will not begin with the `;` character. In addition, the `client` will use the `V1` API endpoint when uploading profiles.
Ran the gProfiler with and without the new option. I've made sure that the correct API endpoint is used, and the profile content is as expected.
=> Add an option to use the legacy profile upload API

gprofiler/profilers/java.py
* Not all Java processes are the "java" binary (for example: jsvc; might be more)
* Not all "java" processes actually have libjvm.so loaded.
This approach is better.
Avoid missing processes for profiling.
Our tests.
=> java: Identify processes to profile by existence of libjvm.so

gprofiler/profilers/python.py, gprofiler/utils.py
Adds timeouts to `run_process()` and use them when running py-spy, because we've seen py-spy hanging already.
Later on we can add timeouts to other executions of processes in gProfiler.
Prevent py-spy hangs from hanging gProfiler entirely.
I changed `timeout=self._duration + self._EXTRA_TIMEOUT` to `timeout=self._duration - self._EXTRA_TIMEOUT` and all py-spys failed with proper error.
The CI will test the usual case of no timeout.
=> Add timeout to py-spy run

gprofiler/profilers/python.py, gprofiler/utils.py
We used to bail out on this case (that `assert`).
If it ever happens, for whatever reason, it will continue happening forever for that invocation of gProfiler, because we don't take care of it and just keep bailing out on every iteration.
This has 2 parts:
* Always remove the output file, even if reading / decoding of it fails.
* If numerous output files are found, remove all and use the last.
I saw it triggered by a `UnicodeDecodeError` inside `read_text`. This PR, of course, does not solve that issue, but only attempts to fix up profiling in case that issue was only a one-timer.
Automatically fix up the described error case, without user intervention/restart.
T.B.A
=> python: pyperf: Automatically fix up numerous output-files situations

gprofiler/profilers/python.py
Be graceful if process exits before starting py-spy / during py-spy setup.
Avoid annoying errors in the log.
Checked both new flows (injected a sleep in `_select_processes_to_profile` so I can see how stale PIDs are handled)
=> python: pyspy: Be graceful on process exits before profiling

gprofiler/main.py, gprofiler/utils.py
Errors while trying to take the lock are common (well, now it's the first "privileged" thing we're trying to do).
Running as a container w/o `--privileged` currently yields:
```
Exception in thread Thread-1:
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/app/gprofiler/utils.py", line 362, in _switch_and_run
if not is_same_ns(target_pid, nstype):
File "/app/gprofiler/utils.py", line 291, in is_same_ns
return os.stat(f"/proc/self/ns/{nstype}").st_ino == os.stat(f"/proc/{pid}/ns/{nstype}").st_ino
PermissionError: [Errno 13] Permission denied: '/proc/1/ns/net'
Could not acquire gProfiler's lock. Is it already running? …
```
=> Differentiate between "lock taken" and "error while trying to take the lock"

README.md, deploy/docker-compose/docker-compose.yml, deploy/k8s/gprofiler.yaml
=> Use "granulate-gprofiler" as container name

README.md, gprofiler/main.py
Change exit code to 0 when failing to grab the mutex. This help gprofiler container avoid
excessive restarts when running using K8s or docker
Exiting with exit code 0 when failing to grab the mutex.
=> bugfix: gProfiler excessive restarts when run in a container and failing to grab the mutex

gprofiler/main.py
The title
If initialization of e.g `phpspy` fails, it may be relevant for the user (if they want to profile PHP) and it may not be. More commonly, it won't be, as there are many profilers. So it's best if initialization failures are just logged, instead of hard failing.
```
diff --git a/gprofiler/profilers/php.py b/gprofiler/profilers/php.py
index b7fe39f..47e49fb 100644
--- a/gprofiler/profilers/php.py
+++ b/gprofiler/profilers/php.py
@@ -92,7 +92,7 @@ class PHPSpyProfiler(ProfilerBase):
phpspy_dir = os.path.dirname(phpspy_path)
env = os.environ.copy()
env["PATH"] = f"{env.get('PATH')}:{phpspy_dir}"
-        process = start_process(cmd, env=env, via_staticx=False)
+        process = start_process(["bash", "-c", "echo blaa && exit 1"], env=env, via_staticx=False)
```
then
```
[2021-08-22 …
```
=> Continue if the start() method of any profiler fails (and avoid using it)

gprofiler/profilers/java.py, gprofiler/profilers/python.py, gprofiler/profilers/ruby.py, gprofiler/utils.py
psutil.Process.name() seems to get it from /proc/pid/stat, but it returns
very long strings (over the 16 bytes of comm) so it doesn't make sense. It seems like
its return value is the first entry from /proc/pid/cmdline.
Anyway, we'll just get /proc/pid/comm to be accurate with what "perf" gets.
@DanielShaulov , I think it's better than `basename(readlink(/proc/pid/exe))` because it maintains consistency with perf.
Consistency with perf + avoid overly long strings.
=> Use /proc/pid/comm as the first stack of process profiles

gprofiler/profilers/java.py, tests/test_sanity.py
We've seen it fail, for whatever reasons (e.g invoking via /proc/pid/exe doesn't work).
Such safety checks should be override-able so we can skip them if we know it's okay, but
they fail us.
Ran with `--java-no-version-check` and saw that this line:
```
[2021-08-22 22:59:40,095] DEBUG: gprofiler.utils: Running command: (/proc/40/exe -version)
```
is gone.
=> java: Allow skipping the version check

gprofiler/profilers/php.py
Provides information on why `phpspy`'s startup has failed.
```
diff --git a/gprofiler/profilers/php.py b/gprofiler/profilers/php.py
index eaa0012..f758952 100644
--- a/gprofiler/profilers/php.py
+++ b/gprofiler/profilers/php.py
@@ -92,7 +92,7 @@ class PHPSpyProfiler(ProfilerBase):
phpspy_dir = os.path.dirname(phpspy_path)
env = os.environ.copy()
env["PATH"] = f"{env.get('PATH')}:{phpspy_dir}"
-        process = start_process(cmd, env=env, via_staticx=False)
+        process = start_process(["bash", "-c", "echo blaa && exit 1"], env=env, via_staticx=False)
```
then
```
[2021-08-22 22:38:51,184] INFO: gprofiler.profilers.php: Starting profiling of PHP processes with phpspy
[2021-08-22 22:38:51,185] DEBUG: gprofiler.utils: Running command: (bash -c echo blaa && exit 1)
[2021-08-22 …
```
=> php: Log stderr & stdout if startup fails

Dockerfile, pyi.Dockerfile, scripts/async_profiler_build.sh, scripts/perf_env.sh
Nothing major, just simplify the build script & remove the complex COPY & `tar -xf` lines. Copy only the files we need from the build.
=> Simplify async-profiler's build & COPY statements

.github/workflows/build.yml, scripts/build_aarch64_container.sh, scripts/libunwind_build.sh
Implements CD for Aarch64 images. After this PR, images pushed by our CD will be a "manifest list" (whatever that means) that has 2 images, the Aarch64 one and the x86_64 one.
I ran it in a private repo and verified the resulting image are pull-able and run-able on both Aarch64 and x86_64.
I do want to test it with older Docker version (I don't know if older versions handle all of this manifests thing)
=> Build & push Docker image manifest that includes Aarch64

gprofiler/gprofiler_types.py, gprofiler/main.py, gprofiler/profilers/python.py
The title :)
Passing 0 works for disabling user stacks, which is sometimes desired.
=> python: PyPerf: Allow passing 0 for --pyperf-user-stacks-pages

gprofiler/utils.py
Get process comm from `/proc/PID/status` instead of `/proc/PID/comm`, as it only exists since kernel 2.6.33
gProfiler fails in kernel versions prior to 2.6.33.
=> Get process comm from /proc/PID/status instead of /proc/PID/comm

gprofiler/profilers/python.py
See py-spy commit https://github.com/benfred/py-spy/commit/290584dde76834599d66d74b64165dfe9a357ef5,
SIGINT just raises a flag telling it to stop (makes sense, since it still dumps output etc).
But if py-spy is stuck for whatever reason, it won't be stopped by this signal.
SIGTERM is not handled by py-spy so it will exit immediately.
=> python: py-spy: Use SIGTERM to stop it

README.md, gprofiler/profilers/php.py, tests/conftest.py
Don't run `phpspy` by default. It seems to leak memory in some cases. Let's enable it only when needed.
=> Disable PHP profiling by default

gprofiler/merge.py, gprofiler/profilers/python.py, gprofiler/profilers/ruby.py, gprofiler/utils.py
Wrap all code paths with removal of temporary output files, properly this time.
Avoid leaving leftovers which, over time, increase gProfiler's disk usage.
* CI
* Will test manually with cases that previously resulted in a file being leaked (e.g timeout / error)
=> python, ruby: Properly wrap all code paths with removal of temporary files

Dockerfile, gprofiler/profilers/java.py, gprofiler/profilers/perf.py, gprofiler/utils.py, pyi.Dockerfile, scripts/async_profiler_build.sh, tests/containers/java/Fibonacci.java, tests/test_java.py, tests/test_sanity.py, tests/utils.py
Bases on https://github.com/jvm-profiling-tools/async-profiler/pull/411 to use AP's CPU mode.
We'll have kernel stacks for profiled Java processes :)
Locally. ~~I'll add some test as well.~~ added a test
=> java: async-profiler v2.5 and CPU mode with fdtransfer

README.md, scripts/pyperf_build.sh, scripts/pyspy_build.sh
* Upgrade py-spy to v0.3.10 (include Python 3.10 support :)
* Upgrade PyPerf to v1.1.2 (allow longer file names).
Rebasing our py-spy patches resulted in no changes:
```
$ git range-diff v0.3.9..v0.3.9g1 v0.3.10..v0.3.10g1 | cat
1:  7952b8c = 1:  b23d457 Don't gather thread activity for all threads when --nonblocking is provided
2:  250396d = 2:  f30e48f Don't grab stack trace of non-GIL threads when --gil is provided
3:  c057201 = 3:  480deec Add a suffix to the stacks to easily identify Python stacks (#1)
```
=> Upgrade python profilers

gprofiler/profilers/python.py
=> Fix typo in python.py

README.md, gprofiler/profilers/python.py
Improves user friendliness
I tried both `pyspy` and `py-spy`.
=> python: Allow passing "--python-mode py-spy" as well as "pyspy"

gprofiler/profilers/java.py, gprofiler/profilers/registry.py, tests/test_java.py, tests/test_sanity.py
Allows passing `safemode` to async-profiler. This lets async-profiler operate in a safer mode, see this comment for example: https://github.com/jvm-profiling-tools/async-profiler/issues/501#issuecomment-968133103
Profiling Java now w/o passing this new parameter, causes `safemode=0` to be passed (which is the default in AP's code).
Passing e.g 127 passes `safemode=127` as expected.
=> java: Allow passing safemode to async-profiler

deploy/dataflow/setup.py, gprofiler/client.py, gprofiler/docker_client.py, gprofiler/log.py, gprofiler/main.py, gprofiler/metadata/cloud_metadata.py, gprofiler/metadata/system_metadata.py, gprofiler/profilers/__init__.py, gprofiler/profilers/factory.py, gprofiler/profilers/perf.py, gprofiler/profilers/php.py, gprofiler/profilers/python.py, gprofiler/profilers/ruby.py, gprofiler/utils.py, lint.sh
@d3dave , it was disabled by you in #47 . I don't recall why. Now, it's become quite annoying for me to manually fix strings :sweat_smile: 
Personally I prefer `"` to `'` but I really don't mind configuring either (I suppose `black` supports it?). Just let's keep it a standard and let the linter do its job.
@alonbentamar tagging you as well because I know you're up for `'`s.
=> lint: Enable black's string normalization

gprofiler/main.py
Lets gProfiler know it was invoked by a specific process; and should that process go down for whatever
reason, gProfiler should go down as well.
Automatically stop gProfiler if it was started by another component which has gone down.
* PID not running - gProfiler doesn't start
* PID running then stops - gProfiler stops
* PID running then zombie - gProfiler stops
=> Add --controller-pid

gprofiler/profilers/java.py
We have decided to enable it as a precaution; we'll see how this affects the profiles (now async-profiler might produce more `unknown_*` frames).
=> java: Enable async-profiler's safemode by default

gprofiler/main.py, gprofiler/profilers/java.py, gprofiler/profilers/python.py, gprofiler/utils.py, tests/conftest.py, tests/containers/java/Dockerfile, tests/containers/java/musl.Dockerfile, tests/test_java.py, tests/test_sanity.py
If java process terminates due to an error, detect it and report a log message. In addition, extract siginfo, native frames, vm info, and container info from the hotspot log and report them in our log.
Debugging async-profiler misbehaviors.
1. Changed async-profiler to force a crash.
2. Started OpenJDK example process.
3. Ran gprofiler built from this branch.
4. Ran crashing async-profiler.
```
[15:40:25] Found Hotspot error log at /proc/1/root/home/ubuntu/jbb/21-11-16_153905/hs_err_pid32629.log
[15:40:25] Pid 32629 Hotspot VM info: OpenJDK 64-Bit Server VM (25.292-b10) for linux-amd64 JRE (1.8.0_292-8u292-b10-0ubuntu1~18.04-b10), built on Apr 21 2021 11:46:09 by "buildd" with gcc 7.5.0
[15:40:25] Pid 32629 Hotspot siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: …
```
=> Java: Check for Hotspot error files after process termination

gprofiler/profilers/java.py, tests/test_java.py
When a hotspot error file is detected for a profiled process, disable current and future profiling of all java processes
Added pytest tests
=> java: Disabling java profiling on hotspot error file detection

Dockerfile, README.md, deploy/docker-compose/docker-compose.yml, deploy/ecs/gprofiler_task_definition.json, deploy/k8s/gprofiler.yaml, gprofiler/metadata/system_metadata.py, gprofiler/profilers/python.py, pyi.Dockerfile, scripts/bcc_helpers_build.sh, scripts/perf_build.sh, scripts/pyperf_build.sh, tests/conftest.py, tests/test_executable.py, tests/test_java.py, tests/test_sanity.py, tests/utils.py
This is ~~a PoC of running~~ PyPerf w/o kernel headers.
~~Container mode doesn't work yet. Running `get_fs_offset` fails. Also when I add `memlock=999999999` and  `-v /sys/kernel/tracing....` (which bypass some of the erros). The `get_fs_offset` program still fails and I need to debug that.~~
~~Exe mode works - I have deleted my local kernel headers. and PyPerf still works :)~~
Both container & exe work.
Based on:
* https://github.com/Granulate/bcc/pull/28
* https://github.com/Jongy/bpf_get_fs_offset
* https://github.com/Jongy/bpf_get_stack_offset
Tasks left:
Test `get_fs_offset` and `get_stack_offset` on more kernel versions:
=> python: PyPerf w/o kernel headers :)

gprofiler/profilers/java.py
Apparently it was removed in f006e0044391f. We will think of another solution to limiting
the frame buffer size (so async-profilers left alive for whatever reason, do not consume memory forever)
We'll avoid these errors once https://github.com/jvm-profiling-tools/async-profiler/pull/503 is merged :)
CI
=> java: async-profiler: Remove framebuf parameter

tests/test_executable.py
It fails with the following error:
[2021-11-23 11:10:14,538] DEBUG: gprofiler.profilers.python: eBPF profiler error: [Errno 2] No such file or directory: 'mount': 'mount'
Cherry-picked from https://github.com/Granulate/gprofiler/pull/221.
=> tests: Skip PyPerf test on centos:6

.flake8, .github/workflows/ci.yml, .github/workflows/release.yml, .gitmodules, .isort.cfg, Dockerfile, dev-requirements.txt, gprofiler/main.py, gprofiler/profilers/java.py, gprofiler/profilers/perf.py, gprofiler/utils.py, mypy.ini, pyi.Dockerfile, requirements.txt, setup.py
* Move namespace utils to granulate_utils so they can be reused by other components besides gProfiler.
* Make granulate_utils a submodule
* Upgrade version of granulate_utils (after https://github.com/Granulate/granulate-utils/pull/8)
=> Move namespace utils to granulate_utils and make granulate_utils a submodule

Dockerfile, gprofiler/kernel_messages.py, gprofiler/profilers/java.py, tests/test_java.py
* Put log params in extras for easier parsing
* Merge PIDs tracking
* Make sure that kernel messages & proc_events are checked for PIDs (i.e don't remove from the profiled PIDs list immediately)
* Start proc_events in init net NS because it wouldn't work otherwise.
After https://github.com/Granulate/gprofiler/pull/226
=> java: Cleanup & fixes for the next release

gprofiler/profilers/java.py
1. Strip `-ea` suffix
2. Log parsing exception if any
3. Add JDK 14 to minimal versions
=> java: Add JDK 14 on alpine to minimal versions

scripts/async_profiler_build_shared.sh
The new version is built statically with libgcc, which was required for Java
based on the image 'openjdk:14-alpine' as it doesn't have libgcc installed.
I can't think of a reason *not* to build statically always, hence enabling it
for all builds.
Tested profiling on Java from `openjdk:14-alpine`, hasn't worked before, does work now.
=> java: Upgrade AP for a static libgcc build

gprofiler/profilers/java.py
Log only upon signal exits - we don't care about the rest. We care specifically about SIGKILL, SIGTERM which are common sources of trouble.
* SIGKILL can't be caught, so it results in exit code `0x0009` which makes `WIFSIGNALED` return true and the signal code is 9.
* I checked SIGSEGV, SIGILL. They are caught by the JVM and cause generation of hs_err files; then the JVM exits with SIGABRT (`VMError::report_and_die` calls `os::die` which calls `abort`). So the signal code is 6.
* SIGTERM is the last question. The JVM handles it (seen in `strace -f`) and eventually does `exit_group(143)`. I have yet to find where it happens in JVM sources.
I have found this gem, tho:
```
} else if (WIFSIGNALED(status)) {
// The child exited because of a signal
// The best value to return is 0x80 + signal …
```
=> java: Filter signal codes only in proc_events callback (from all non-zero exit codes)

tests/conftest.py, tests/containers/python/Dockerfile, tests/test_executable.py
Add tests that run AP, py-spy & rbspy (and gProfiler itself) in a container without `--privileged`. This resembles Databricks, Fargate etc.
=> tests: Test gProfiler with low privileges

gprofiler/profilers/java.py
We want the ability to be very strict on error detection. This is possibly too strict (segfaults in non-profiled processes are most likely not related to us...) but we'll start very strict and lower the bar as we go.
The "PID in message" check will help us identify if our regex on OOM/signals miss anything (or if there's any other type of bad message we should be looking at). I hope it won't catch too many false positives.
* Triggered an OOM with `docker run -it -m 6m python` and made sure Java profiling stops
* Triggered a segfault with `main(){*(int*)0=0;}` and made sure Java profiling stops
* Wrote a profiled PID to the kernel log (`echo 374075 | sudo tee /dev/kmsg`) and made sure Java profiling stops. It's funny that it works - the kernel does flag messages coming from usermode, we …
=> java: Paranoid profiling stop on suspicious events in kernel messages

gprofiler/profilers/python.py
Leftovers (from previous runs / from test()) may later be caught by our _dump().
I encountered it while running gProfiler and the output graph would have 1 sample of PyPerf... Which is the sample from the `test()` call.
After this fix, running gProfiler (`--no-perf` and just a Python app being profiled by PyPerf) correctly works and gives the expected number of samples; hence, using the real output file.
=> python: pyperf: Remove output files before starting

.github/workflows/build-executable-test-deploy.yml
So last release (1.2.9) I had to upload the files manually :/
=> ci: deploy-executable needs build-executable, not test-executable

gprofiler/__init__.py, scripts/async_profiler_build_shared.sh
Hotfix for the mentioned bug.
CI
Tested by `strace`ing a Java application and running gProfiler alongside. In the trace I can find `EBADF`. On this branch, I don't see the `EBADF` anymore, and there's only one `close` call.
=> gProfiler 1.2.10 & upgrade Java's async-profiler

gprofiler/profilers/registry.py
In order to be passed to the relevant profiler, the `dest` of profiler-specific arguments must be prefixed with the profiler's name. This PR `assert`s they're named correctly.
I tried to add an argument without knowing this and spent some good amount of time debugging that could've been saved with this `assert`.
Just ran gProfiler and saw that this `assert` isn't triggered, and then ran it again with a wrong arg `dest`.
=> Prevent registering of profiler arguments with a wrong dest name

scripts/bcc_helpers_build.sh
v0.0.3 avoids BPF accesses to non-canonical addresses, which may trigger a `WARN_ONCE` that we prefer to avoid :)
See the fix in https://github.com/Jongy/bpf_get_stack_offset/commit/54b70ee65708cc8d3d7817277e82376d95205356.
Avoid triggering kernel warnings during gProfiler's run.
CI.
I have tested the fixed `get_stack_offset` program on a 5.4 kernel which triggers the `WARN_ONCE` on v0.0.2; and v0.0.3 no longer triggers it.
I have also tested v0.0.3 on 4.15.0-72-generic, which is old enough to have the limit of 4096 instructions. The program still runs (that is, the instructions I added in the loop do not cause us to exceed the limit.
=> python: pyperf: Bump bpf_get_stack_offset version to v0.0.3

gprofiler/profilers/python.py, tests/test_sanity.py
Surround module info in stacks with `[]` instead of `()` and separate the package name from the package version with `==` instead of `-`.
For example, this symbol:
`scapy.utils.PcapReader.read_packet (/usr/lib/python3.6/site-packages/scapy/utils.py:1347 (scapy-2.4.5))_[p]`
Will be now presented like this:
`scapy.utils.PcapReader.read_packet (/usr/lib/python3.6/site-packages/scapy/utils.py:1347 [scapy==2.4.5])_[p]`
* Regular parenthesis are already used to separate the metadata section of the symbol, so using another kind of parenthesis for the package info is more noticeable and easier to read.
* The character `"-"` can be part of a package name or version, so it's better to use characters that can't appear in either of them.
=> Python: Make packages info representation more distinguishable

gprofiler/profilers/java.py
The minimum version I've set is the one I have tested on.
```
bash-4.4# java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
bash-4.4# java Target
```
from (`openjdk:17`).
Support new JDK versions.
Tested profiling a demo app in `openjdk:17` container.
=> java: Add JDK 17 to supported versions

gprofiler/merge.py
Re-using the same logic from dwarf scaling to process scaling - instead of rounding the samples to nearest integer we call `random` and `ceil` if the non-integer part is lower than the result, so over time the sample counts are more correct.
In addition - for cases where the result is 0, we remove the whole stack from the results. The behavior for dwarf scaling was to just leave the old value which is bogus, and for perf it was to leave the stack with a zero count which spams the backend and enlarges the output files.
None
CI will test it
=> merge: Scale process counts using random instead of just rounding

.github/workflows/build-container-and-test.yml, scripts/pyperf_build.sh
* Support Python 3.10 offsets - so PyPerf can profile Python 3.10 apps :)
* Fix native stacks that were broken for certain kernel versions since PyPerf v1.2.0;
should now work for all versions.
* Enable CI on Python 3.10
Support PyPerf with Python 3.10, and fix native stacks so it works everywhere :)
PyPerf was tested on kernel versions such as `4.15.0-72-generic` that have previously failed to get native stacks. Now they succeed. Also see more in https://github.com/Granulate/bcc/pull/32.
And also, was tested by CI.
=> python: Upgrade PyPerf & run the CI on Python 3.10

gprofiler/profilers/java.py, gprofiler/profilers/registry.py, tests/test_java.py, tests/test_sanity.py
Now, passing plain --java-safemode implies all options.
Alternatively, one can pass --java-safemode=a,b,c to enable only a, b, c.
Finer control on which features are enabled.
Note that, for most features that revolve around disabling the profiler - they are enabled anyway but do not cause disabling of the Java profiler if the flag is not enabled.
Test disabling each appropriate flag, and test it again with `--java-safemode=all`.
Additionally, those 2 are unrelated to disabling the Java profiler:
=> java: Expand --java-safemode into a set of options

gprofiler/profilers/java.py
Based on https://github.com/Granulate/gprofiler/pull/248
Use detected "signaled profiled processes" from proc_events to disable profiling when the safemode option is on.
Improve our safemode; specifically, this helps in the cases where the hs_err file is not available / will not be available (e.g because the target process runs in a container that'll exit once the process exits; so we won't see the file as the container went down).
=> java: Disable profiling (safemode) on proc_events signals

gprofiler/merge.py, gprofiler/metadata/application_identifiers.py
1. Don't insert Java app id if no `-jar` arg is present (bugfix)
2. Keep the original first frame - insert the app id frame second.
=> app ids: Keep original frame

gprofiler/__init__.py, gprofiler/merge.py, gprofiler/metadata/application_identifiers.py
Saddest bug I've had in the last year, I think.
When I made the `appid` change, I tested it on a Python in `while 1: pass` so it really had only 1 stack and this issue didn't manifest :/
=> gProfiler 1.2.12 + small bugfix

gprofiler/profilers/python.py
We now trust PyPerf enough to avoid the need to fallback once it hangs/crashes/whatever. So let's stay with it even if it happens... and we'll monitor logs to understand in which cases this happens, and how can we avoid it.
=> python: pyperf: Restart PyPerf if it fails

gprofiler/profilers/java.py, scripts/async_profiler_build_shared.sh
Upgrade async-profiler to v2.6g1. This brings many fixes & stability improvements.
Additionally, since we're now based on https://github.com/jvm-profiling-tools/async-profiler/commit/9087bc57d80f622b8f4e0eabcf06dbf9cb54e815, we don't need the `mlock` games anymore, so I have removed them.
* CI
=> java: Upgrade async-profiler to v2.6g1

gprofiler/profilers/java.py, tests/test_java.py, tests/test_sanity.py, tests/utils.py
When profiling of a process is skipped by gProfiler for whatever reason, the following happens:
* In perf-less mode (`--perf-mode=none`) - we won't see its stacks and we won't know it existed.
* In standard mode, gProfiler will use the samples collected by `perf` (if any) when merging the stacks. So we'll see the native Java code, which is seldom interesting.
This PR amends the Java profiler to return a specialized stack per "skip" case (safemode, AP already loaded in a process, ...). This way, the user sees the cause of the error immediately, and doesn't have to skim through the logs in order to understand. Also, it makes the skip explicit ("gProfiler found this process and decided to skip", instead of "maybe gProfiler missed it..."). Explicitness is good.
Make it easier to understand …
=> java: Show a "profiling skipped" stack when profiling is skipped for a process

gprofiler/profilers/java.py, tests/test_java.py, tests/test_sanity.py
AP itself is highly configurable. This option will allow trying out different AP configurations, even if they are not yet supported by gProfiler's interface.
Added AP option `dot` and saw that Java class names are now using `.` instead of `/`.
=> java: Add --java-async-profiler-args, allowing to send arbitrary extra args to AP

gprofiler/profilers/java.py
This is not deemed required now, and it causes too many `unknown_Java` frames. We will classify which safemode options are relevant, and enable just them.
=> java: Set --java-async-profiler-safemode=0 by default

gprofiler/profilers/java.py
We see errors like:
Java HotSpot(TM) 64-Bit Server VM warning: Insufficient space for shared memory file:
8703
Try using the -Djava.io.tmpdir= option to select an alternate temp location.
Don't care about them, so I am stripping everything before the expected first line.
CI
=> java: Strip unrelated output prefix lines in "java -version"

gprofiler/main.py, gprofiler/profilers/java.py, gprofiler/profilers/python.py, gprofiler/utils.py, tests/conftest.py, tests/test_java.py, tests/test_sanity.py, tests/utils.py
Based on:
* https://github.com/Granulate/gprofiler/pull/264
* https://github.com/Granulate/gprofiler/pull/263
* https://github.com/Granulate/gprofiler/pull/262
This PR includes 2 changes :sweat_smile: it was convenient to write them together.
* We now pass the `timeout` parameter, added to [AP v2.6](https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v2.6). This ensures we prevent AP from running forever, if we don't stop it for whatever reason.
* We try to read the AP output file even if the profiled process has exited during profiling. This helps when profiling short processes - as the last "duration" of profiling may be lost, if the process exits e.g 50 seconds into the 60 seconds profiling session.
* AP timeouts - improves robustness; we will automatically stop Java …
=> java: Use AP timeouts & read output file upon process exit

gprofiler/profilers/java.py, gprofiler/profilers/python.py, gprofiler/utils.py
See comment on process_exe() - it correctly raises ZombieProcess (which is a subclass
of NoSuchProcess) for zombie processes.
gProfiler should treat this error as processes going down.
These are all invocations of `Process.exe()` in gProfiler.
See https://github.com/giampaolo/psutil/pull/2062 which solves the issue in `psutil`.
Currently we don't handle it as "process is down", so we get unrelated errors like `Non-java basenamed process, skipping... (disable --java-safemode to profile it anyway)` with `exe=""`, which happens because the process is a zombie, so I actually want it ignored.
=> Use process_exe() everywhere

gprofiler/metadata/application_identifiers.py
Fix a small bug, when trying to identify applications, we may parse uwsgi config file which is an ini file, the file format allows overriding config options, although by default Python's [configparser](https://docs.python.org/3.9/library/configparser.html)
raises exception upon this scenario, this PR fixes this issue by disabling this behavior. 
See explanation below.
=> Bugfix/ uwsgi-config-file-parsing

gprofiler/metadata/application_identifiers.py
Support another "flavor" of proc names that gunicorn uses, depending on its config.
I ran `Process(pid).cmdline()` on a system which has a gunicorn that uses `setproctitle()`. I took the output and ran it via this new class - and it returned the correct appid. This was the input:
```
['gunicorn: worker [myapp.wsgi:app]', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
```
=> appids: Support gunicorns which use setproctitle()

gprofiler/profilers/java.py, gprofiler/profilers/python.py, gprofiler/profilers/ruby.py, gprofiler/utils/__init__.py, gprofiler/utils/process.py
Avoid the `FileNotFoundError` - `NoSuchProcess` is handled gracefully.
=> utils: Raise NoSuchProcess from process_comm() if process is missing

dev-requirements.txt, gprofiler/client.py, gprofiler/docker_client.py, gprofiler/exceptions.py, gprofiler/gprofiler_types.py, gprofiler/kernel_messages.py, gprofiler/log.py, gprofiler/main.py, gprofiler/merge.py, gprofiler/metadata/py_module_version.py, gprofiler/metadata/system_metadata.py, gprofiler/profilers/java.py, gprofiler/profilers/perf.py, gprofiler/profilers/php.py, gprofiler/profilers/profiler_base.py, gprofiler/profilers/python.py, gprofiler/profilers/registry.py, gprofiler/profilers/ruby.py, gprofiler/system_metrics.py, gprofiler/usage_loggers.py, gprofiler/utils.py, gprofiler/utils/__init__.py, mypy.ini, tests/conftest.py, tests/containers/python/lister.py, tests/test_java.py, tests/test_libpython.py, tests/test_sanity.py, tests/type_utils.py, tests/utils.py
From now on, mypy will be set to `strict = True` it its config file.
`pre-commit` and CI both run `lint.sh` that runs `mypy .`, but mypy wasn't strict, so it didn't check much, now it will.
* Made sure `pre-commit` hook works
* Made sure CI catches problems
=> mypy: Enable mypy strict mode

gprofiler/profilers/java.py, gprofiler/profilers/profiler_base.py, gprofiler/profilers/python.py
As discussed in https://github.com/Granulate/gprofiler/pull/263#discussion_r785871160. The cases fixed here are much less common, but let's have them covered as well, and I changed the interface.
~~We still don't handle exceptions raised in `_profile_process`. I'll think how we want them handled - perhaps, automatically converted to an error stack by `ProcessProfilerBase.snapshot`?~~
* CI
=> Return profiling error stack in all error/skip cases of _profile_process

gprofiler/metadata/py_module_version.py
Previously it was possible to get an incorrect Python versions in cases where the python versions regex matched a wrong string.
This PR prevents it by narrowing down the possible Python versions to expected ones only (2.7 and 3.5-3.12), and by not presenting a Python version in case the regex had more than a single match.
I tested it in a container with an application for which we previously got an incorrect version (conveniently, gprofiler itself...).
=> Python: Bugfix: Don't emit incorrect Python versions

README.md
Add AWS EMR Installation instructions to project README
Make gProfiler installation easy and well explained on AWS EMR.
=> README: add AWS EMR instructions

gprofiler/utils/__init__.py
Before:
```
[2022-02-15 01:15:44,919] DEBUG: gprofiler.utils: (['/app/gprofiler/resources/java/jattach', '170186', 'load', '/tmp/gprofiler_tmp/async-profiler-v2.6g1/glibc/libasyncProfiler.so', 'true', 'stop,log=/tmp/gprofiler_tmp/tmpz041724c/async-profiler-170186.log,file=/tmp/gprofiler_tmp/tmpz041724c/async-profiler-170186.output,collapsed,ann,sig']) stdout: Connected to remote JVM
JVM response code = 0
0
....
```
After:
```
[2022-02-15 01:17:52,956] DEBUG: gprofiler.utils: (['/app/gprofiler/resources/java/jattach', '170186', 'load', '/tmp/gprofiler_tmp/async-profiler-v2.6g1/glibc/libasyncProfiler.so', 'true', 'stop,log=/tmp/gprofiler_tmp/tmpb521zx97/async-profiler-170186.log,file=/tmp/gprofiler_tmp/tmpb521zx97/async-profiler-170186.output,collapsed,ann,sig']) stdout: 'Connected to …
```
=> utils: run_process(): repr() output before logging it

scripts/pyperf_build.sh, tests/containers/python/lister.py, tests/test_sanity.py
BCC PR: https://github.com/Granulate/bcc/pull/35
Basically, upgrade PyPerf reference post the fixing PR, and add some tests that would catch the issue explicitly.
I found this using https://github.com/Granulate/gprofiler/pull/268 - which showed me that tests occasionally failed because Python 3.10 was running on the runner (e.g was running our pytest) and it had class names which were read incorrectly - reading random binary data which was later not decoded correctly. That's why it was statistical - because profiling is statistical :/ and sometimes stacks with class names were not encountered in the profile.
Lessons learned: try and test all flows, because some flows that you don't test might be "automatically" tested by your system-wide profiler doing its profiling on random crap on your …
=> python: Fix PyPerf for 3.10

.github/workflows/build-container-and-test.yml, README.md, deploy/docker-compose/docker-compose.yml, deploy/ecs/gprofiler_task_definition.json, deploy/k8s/gprofiler.yaml, deploy/k8s/helm-charts/templates/daemonset.yaml, gprofiler/containers_client.py, gprofiler/main.py, gprofiler/merge.py, lint.sh, requirements.txt, scripts/async_profiler_env_glibc.sh
Builds upon https://github.com/Granulate/granulate-utils/pull/32 and https://github.com/Granulate/granulate-utils/pull/31 which provide unified API to list containers across other runtimes, for container name resolving (up until now we had just Docker, now we've gained support for CRI-based ones in k8s: containerd and cri-o).
Along the way, I no longer require to map the Docker socket. We run as host PID so from now on we'll use `/proc/1/root/var/run/docker.sock` etc.
[Docker is going away in k8s](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/) so resolving names via Docker doesn't work in newer k8s clusters.
1. Tested the API on a local k8s minikube (importing stuff from granulate-utils)
2. Tested gProfiler on my box (Docker) and container names are still …
=> Replace old DockerClient with newer API compatible with Docker and CRI

gprofiler/log.py, gprofiler/profilers/java.py
Solves this:
```
[2022-02-23 10:40:27,597] ERROR: gprofiler.RemoteLogsHandler: Can't serialize extra (extra={'jvm_version': JvmVersion(8.111, 14, 'OpenJDK 64-Bit Server VM'), 'run_id': 'ec30de5e-2c78-4a15-bce9-b740e2b43668', 'cycle_id': 'ec30de5e-2c78-4a15-bce9-b740e2b43668'}), sending empty extra
File "/app/gprofiler/log.py", line 144, in _make_dict_record
json.dumps(extra)
File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
return _default_encoder.encode(obj)
File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File "/usr/lib/python3.8/json/encoder.py", line 179, in default
raise TypeError(f'Object …
```
=> java: repr(jvm_version) in all sites, as it's not serializable

Dockerfile, pyi.Dockerfile, scripts/async_profiler_build_shared.sh, scripts/async_profiler_env_glibc.sh
My trigger for that are the lousy mirrors of CentOS 6, which make our CI flaky.
In any case, it's a hassle to continue using CentOS 6 in any way.
This commit fixes the build to be CentOS 7 based. It's old enough glibc to run on
old kernels, and I verified that the only relevant symbol which required glibc>2.12
now gets versioned to something older as well.
See the fix for AP here: https://github.com/Granulate/async-profiler/commit/0d04078e0586793e852beb11ab285185c447e986
I tested the before & after with https://gist.github.com/Jongy/56f33f4b8a3e04b41d1afb85b47121a1:
before - 
```
glibc version: 2.14
glibcxx version: 3.4.9
```
after -
```
glibc version: 2.4
glibcxx version: 3.4.9
```
and I expect that the executable test on `centos:6` will also cover me here :sweat_smile:
=> Build async-profiler on CentOS 7

gprofiler/profilers/java.py, gprofiler/utils/__init__.py
If e.g `/tmp` is a symlink to `/var/tmp`, then this check would fail. Now it'll pass in either case.
=> java: Fix _check_async_profiler_loaded() for cases where resolved storage path differs

tests/conftest.py, tests/test_libpython.py
From the documentation:
```
rm (bool): Remove intermediate containers. The ``docker build``
command now defaults to ``--rm=true``, but we have kept the old
default of `False` to preserve backward compatibility
```
=> Removes intermediate containers when using docker SDK to build images.

gprofiler/merge.py, gprofiler/metadata/application_identifiers.py, gprofiler/profilers/java.py, gprofiler/profilers/perf.py, gprofiler/profilers/python.py, gprofiler/profilers/ruby.py, lint.sh
Use the `sun.java.command` Java property as app ID for Java applications. This property contains the JAR if the program is run using `-jar`, or the provided main class otherwise. It also contains the arguments passed to the program.
`sun.java.command` is extracted by running `jattach` in `properties` mode for each Java process.
=> Better java app id resolving

gprofiler/metadata/application_identifiers.py, tests/conftest.py
The full path to java app ids might contain random elements, until we
find a good way to strip those, we want to remove this part of the appid.
=> appid: Remove full path from java appid

dev-requirements.txt, gprofiler/metadata/system_metadata.py, scripts/prepare_machine-unknown-linux-musl.sh
* zlib release 1.2.11 was removed from site, probably due to the recently discovered issues, https://twitter.com/taviso/status/1507781911023742976?s=20&t=UEQka6r_9Qm7TQIp2I6ybA
* `click` 8.1.0 breaks with black, a fix was released in 22.3.0, see https://github.com/psf/black/commit/e9681a40dcb3d38b56b301d811bb1c55201fd97e
=> Upgrade Black & zlib

gprofiler/metadata/application_identifiers.py, tests/test_appids.py
Currently, when no app name is given in celery, the resulting app name will be something like `appid: celery: (/opt/dir/.py)`. After this fix it will be `None`.
=> Fix celery app name when no app name is given in args

.gitignore, gprofiler/metadata/application_identifiers.py, tests/test_appids.py
Support appid for celery workers run like `celery -Q queue_name` or `celery --queues queue_name`
=> Support celery appids with queue workers

gprofiler/exceptions.py, gprofiler/main.py, gprofiler/profilers/factory.py
A user probably doesn't want to run gProfiler this way, as no data will be collected.
If gProfiler is run this way, an empty stackcollapsed file is produced.
I tried to make this error pop at the arguments validation stage, which seems more appropriate; but it's not very convenient to do so, and also not very logical (you actually do want to ensure that at least one profiler has been initialized correctly, so you do need to run their initialization code, etc).
See my comment [here](https://github.com/Granulate/gprofiler/issues/327#issuecomment-1083735555).
=> Exit with an error log if all profilers are disabled

README.md
This allows them to begin with a -, otherwise argparse doesn't like it.
Also, normalize the metavars in the docs.
=> docs: Pass --token, --service-name with =

gprofiler/exceptions.py, gprofiler/profilers/java.py, gprofiler/utils/__init__.py, gprofiler/utils/fs.py, tests/conftest.py, tests/test_java.py
When run as a container, we use `/tmp` to place all of our binaries, and expect it to be executable.
When run as an executable, we give the user an opportunity to set a different directory to extract our executables, in case `/tmp` is not executable, to affect staticx & pyinstaller.
But async-profiler remains - as a DSO that is loaded to target profiled processes, and thus must reside on an executable filesystem in the context of a process.
This PR makes sure to find an executable (and writable) directory for each profiled process, and copy libasyncProfiler.so to that directory accordingly.
=> java: Handle /tmp being noexec (on host / container)

scripts/async_profiler_build_shared.sh, tests/containers/java/musl.Dockerfile, tests/test_java.py
Before:
```
root@3994adfa7dcf:/app# for f in  gprofiler/resources/java/*/libasyncProfiler.so ; do echo $f; ldd $f; done
gprofiler/resources/java/glibc/libasyncProfiler.so
linux-vdso.so.1 (0x00007ffe815cf000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f078b380000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f078b35d000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f078b352000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f078b170000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f078b021000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f078b006000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f078ae12000)
/lib64/ld-linux-x86-64.so.2 (0x00007f078b5c6000) …
```
=> java: Upgrade async-profiler (regression in build scripts, not using -static-* flags)

gprofiler/main.py
Add a log message with the values of the final parsed arguments. For example:
```
[22:23:19] gProfiler arguments: Namespace(app_id_args_filters=[], application_metadata=True, collect_metadata=True, collect_metrics=True, config='config.ini', container_names=True, continuous=False, controller_pid=None, duration=60, flamegraph=True, frequency=11, identify_applications=True, java_async_profiler_args=None, java_async_profiler_buildids=False, java_async_profiler_mode='auto', java_async_profiler_safemode=64, java_mode='ap', java_safemode='true', java_version_check=True, log_file='/var/log/gprofiler/gprofiler.log', log_rotate_backup_count=1, log_rotate_max_size=5242880, log_to_server=True, log_usage=False, nodejs_mode='disabled', output_dir='/tmp', perf_dwarf_stack_size=8192, perf_inject=False, …
```
=> Log arguments

gprofiler/utils/fs.py
Function is called concurrently and possibly on the same mnt namespace, so threads collide writing/removing/executing the script.
Easiest way to avoid that is by randomizing its name.
=> utils: fs: Use randomized path for test script

gprofiler/profilers/java.py, tests/utils.py
In some cases it might be to use a higher timeout, even higher than the new 30s, e.g if process is very
loaded and AP takes a long while to dump the traces.
Also - make it configurable as an argument, for next times.
=> java: Increase jattach timeout & make it configurable

.github/workflows/build-container-and-deploy.yml, .github/workflows/build-container-and-test.yml, .github/workflows/build-executable-test-deploy.yml, gprofiler/__init__.py
GitHub actions machines are 2 cores 7 GB RAM. This is not enough for our cross build (Aarch64). CICD for release doesn't complete, see e.g https://github.com/Granulate/gprofiler/actions/runs/2228001665:
```
The hosted runner: GitHub Actions 6 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```
I added a self-hosted runner that's c4.4xlarge, 8 cores 15 GB RAM, hopefully that'll suffice.
=> Use self-hosted runner for heavy builds & gProfiler 1.2.22

gprofiler/profilers/java.py
This gives `JattachTimeout` exception name (plus more nice details) to timeout of jattach, to differentiate them from other `JattachException`s.
Here's how it looks:
```
[2022-04-28 14:26:52,286] ERROR: gprofiler.profilers.profiler_base: JavaProfiler: failed to profile process 576776 (java)
File "/app/gprofiler/profilers/profiler_base.py", line 139, in snapshot
result = future.result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
return self.__get_result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
raise self._exception
File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/app/gprofiler/profilers/java.py", line 843, in …
```
=> java: Extract JattachTimeout from JattachException

gprofiler/profilers/java.py, tests/test_java.py
Based on https://github.com/Granulate/gprofiler/pull/352
After removing `/tmp/.java_pidX`:
```
[2022-04-29 18:36:37,267] DEBUG: gprofiler.utils: (['/app/gprofiler/resources/java/jattach', '691779', 'load', '/tmp/gprofiler_tmp/async-profiler-v2.7g2/glibc/libasyncProfiler.so', 'true', 'start,event=cpu,file=/tmp/gprofiler_tmp/tmpk8bcej93/async-profiler-691779.output,collapsed,ann,sig,interval=10101010,log=/tmp/gprofiler_tmp/tmpk8bcej93/async-profiler-691779.log,fdtransfer,safemode=64,timeout=35']) stderr: 'Could not start attach mechanism: No such file or directory\n'
[2022-04-29 18:36:37,267] ERROR: gprofiler.profilers.profiler_base: JavaProfiler: failed to profile process 691779 (java)
File "/app/gprofiler/profilers/profiler_base.py", line 139, in …
```
=> java: Raise JattachSocketMissing if the attach socket is missing (HS only for now)

.github/workflows/build-container-and-deploy.yml, .github/workflows/build-executable-test-deploy.yml, cmp_tags.sh, scripts/setup_runner_requirements.sh
2 types of fixes:
1. Upon each run, install the necessary requirements (that come preinstalled on gh hosted runners but not on self-hosted obv)
2. Fix things that expect to run on clean env
Those all I fixed manually when I released 1.2.22, making sure that it works fine next release.
=> ci: Install self-hosted requirements & run on dirty environment

gprofiler/utils/perf.py
[17:21:12] Couldn't create the Java profiler, continuing without it
File "gprofiler/profilers/factory.py", line 41, in get_profilers
File "gprofiler/profilers/java.py", line 637, in __init__
File "gprofiler/profilers/java.py", line 654, in _init_ap_mode
File "gprofiler/utils/perf.py", line 19, in can_i_use_perf_events
File "gprofiler/utils/__init__.py", line 265, in run_process
gprofiler.exceptions.CalledProcessError: Command '['/tmp/_MEIYxgsVy/gprofiler/resources/perf', 'record', '-o', '/dev/null', '--', '/bin/true']' returned non-zero exit status 255.
stdout: b''
stderr: b'Permission error mapping pages.\nConsider increasing /proc/sys/kernel/perf_event_mlock_kb,\nor try again with a smaller value of -m/--mmap_pages.\n(current value: 4294967295,0)\n'
I …
=> utils: perf: Catch another case of perf permissions error

exe-requirements.txt, pyi.Dockerfile, scripts/list_needed_libs.sh, scripts/staticx_patch.diff
Closes: https://github.com/Granulate/gprofiler/issues/342
The problem starts with #342  - we needed to solve the glibc issue after upgrading the base image to CentOS 8.
staticx is the easiest solution because that's what we already do for x86_64. However, simply enabling staticx with this patch:
```
diff --git a/pyi.Dockerfile b/pyi.Dockerfile
index 8f855fe..952226b 100644
--- a/pyi.Dockerfile
+++ b/pyi.Dockerfile
@@ -211,7 +211,7 @@ COPY ./scripts/list_needed_libs.sh ./scripts/list_needed_libs.sh
-RUN if [ $(uname -m) != "aarch64" ]; then source scl_source enable devtoolset-8 llvm-toolset-7 && libs=$(./scripts/list_needed_libs.sh) && staticx $libs dist/gprofiler dist/gprofiler; fi
+RUN libs=$(./scripts/list_needed_libs.sh) && staticx $libs dist/gprofiler dist/gprofiler
FROM scratch AS …
```
=> Use staticx for Aarch64 exe builds

README.md
Read the docs :)
See https://github.com/python/cpython/blob/61e008a4ab0b444342f9186efb57207d6fb05092/Lib/urllib/request.py#L2493 for the exact workings behind `requests` selection of proxies. `https_proxy` and `HTTPS_PROXY` will work.
I tested `http_proxy` and verified that it doesn't affect gProfiler indeed.
=> Document HTTP proxies usage

gprofiler/profilers/java.py
1. Profile Zing if Zing VM > 18
2. Don't profile HS 6 - it crashes
3. Refactor & document version checks
=> java: Profile Zing with AP & refactor version checks

scripts/perf_build.sh, scripts/perf_env.sh
~~Hopefully~~ resolves #340 ~~, pending my testing.~~
=> perf: Upgrade elfutils & disable libdebuginfod

gprofiler/profilers/java.py
I see it high in some profiles :)
=> java: Cache is_musl() calls across AsyncProfiledProcess instances

.gitignore, lint.sh
Passing `--skip` to `isort` overrides the configuration from `.isort.cfg`. Also changing the excluded dirs for `black` to `venv` instead of `.venv` since that's apparently the convention for this project (see a few lines up in `lint.sh`).
=> Fix skip folders in lint script

README.md
This is just confusing to handle. Make it the default.
=> README: Always use TMPDIR=/proc/self/cwd

gprofiler/exceptions.py, gprofiler/main.py, gprofiler/profilers/factory.py, gprofiler/profilers/perf.py
1. CRITICAL logs are bad errors that prevent the profiler from operating correctly
2. ERROR logs are stuff we don't expect to happen and might indicate a bug on our code
3. WARN logs are errors we are aware of and can happen
Currently marked 2 bad errors as CRITICAL, more will be added
=> Set critical logs to "CRITICAL"

gprofiler/profilers/java.py
For example - "1.8.0_292-b2"
Also fixes
```
'openjdk version "1.8.0_212-ojdkbuild"\nOpenJDK Runtime Environment (build 1.8.0_212-ojdkbuild-04)\nOpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)\n'
```
=> java: parse_jvm_version(): Handle single-digit build number suffix

scripts/rbspy_build.sh
See [commit](https://github.com/Granulate/rbspy/commit/2ce395058264d2d832d9a89589d52f26ccd55636) in `Granulate/rbspy`
cargo is acting stupid, locally when I build with this change it finally obtains the repo
=> fix: Update rbspy with fix for failing build

gprofiler/profilers/java.py, scripts/async_profiler_build_shared.sh
Upgrade to AP v2.8.2.
Based on https://github.com/Granulate/gprofiler/pull/402
```
$ git range-diff v2.8.1..v2.8.1g2 v2.8.2..v2.8.2g1
1:  0d8b07a =  1:  b2b8710 Replace semicolon in method descriptors to vertical bar, since a semicolon is already used to separate between methods
2:  93e4b5d =  2:  f72c806 Remove the "Profiling started" message
3:  51bb684 =  3:  3e9bf32 Remove the "Profiling stopped" message
4:  4fd3a44 =  4:  902a2e6 Compile statically with libstdc++
5:  700ba3b =  5:  0a9883d Build jattach statically
6:  e898d0f !  6:  027c1cd Enocde buildid+offset of unknown symbols in the frame (#1)
@@ src/codeCache.h: class CodeCache {
-@@ src/profiler.cpp: CodeCache* Profiler::findNativeLibrary(const void* address) {
+@@ src/profiler.cpp: CodeCache* …
```
=> java: Upgrade to AP v2.8.2

scripts/async_profiler_build_shared.sh
```
$ git range-diff v2.8.2..v2.8.2g2 v2.8.3..v2.8.3g1
1:  9ec48d9 <  -:  ------- Could not recreate perf_event after the first failure
2:  cc1682d <  -:  ------- Handle different versions of Zing properly
3:  5ca36ed =  1:  f03014d Replace semicolon in method descriptors to vertical bar, since a semicolon is already used to separate between methods
4:  cedaa2f =  2:  56daea2 Remove the "Profiling started" message
5:  670f3f1 =  3:  e406f18 Remove the "Profiling stopped" message
6:  60ed4cb =  4:  7a4312d Compile statically with libstdc++
7:  7495121 =  5:  52692de Build jattach statically
8:  dd89f6e =  6:  0edb237 Enocde buildid+offset of unknown symbols in the frame (#1)
9:  944102d =  7:  0c51507 Build fdtransfer statically
10:  9e6b836 =  8:  114a86f Compile statically with libgcc …
```
=> java: Upgrade async-profiler v2.8.3g1

gprofiler/merge.py, gprofiler/profilers/perf.py, tests/conftest.py, tests/containers/native/dwarf.Dockerfile, tests/containers/native/fp.Dockerfile, tests/containers/native/native.c, tests/test_merge.py, tests/test_perf.py, tests/utils.py
These sanity test FP, DWARF and smart modes on 2 applications: one built with FP only, and one built without
FP but with DWARF.
=> Add perf tests

gprofiler/merge.py
This field used to be "cpu-clock:", with the new perf (and on a recent kernel) I get "cpu_core/cycles/",
so add _ and / to the pattern.
It's probably for the better to remove this complex regex and remain only with parsing the stack itself. I didn't want to make a larger change at this point, given that this already works, and that we don't have good tests coverage here.
=> perf: Parse new event family names

gprofiler/metadata/system_metadata.py, requirements.txt
Sanity tested on my box: `gprofiler: Linux distribution: Ubuntu | 22.04 | Jammy Jellyfish`.
The less `type: ignore` the less nightmares I might have
=> requirements Upgrade 'distro'

README.md, gprofiler/profilers/php.py, scripts/phpspy_build.sh, scripts/phpspy_env.sh
phpspy test results (on our branch):
```
TEST tests/test_varpeek.sh
process_vm_readv: No such process
OK   varpeek
process_vm_readv: No such process
OK   varpeek
TEST tests/test_pgrep_time_limit.sh
main_pgrep finished gracefully
ERR  frame_1
expected=^1 <main> <internal>:-1$
actual=
TEST tests/test_pgrep_trace_limit.sh
main_pgrep finished gracefully
ERR  exit_code=124
TEST tests/test_time_limit.sh
OK   include_sleep
TEST tests/test_child.sh
OK   req_uri
ERR  req_ts
expected=^# ts = \d+\.\d+$
actual=
0 usleep <internal>:-1
1 <main> <internal>:-1
TEST tests/test_verbose.sh
OK   verbose_pid
OK   frame_1
OK   verbose_ts
OK   frame_0
TEST tests/test_mem.sh   
SKIP alloc_globals symbol not found
TEST tests/test_flamegraph.sh
OK   flamegraph
TEST tests/test_filter.sh
process_vm_readv: No such …
```
=> Enable phpspy for Aarch64

deploy/dataproc/gprofiler_initialization_action.sh, deploy/docker-compose/docker-compose.yml, deploy/ecs/gprofiler_task_definition.json, deploy/k8s/gprofiler.yaml, deploy/k8s/helm-charts/templates/daemonset.yaml, deploy/systemd/granulate-gprofiler.service.template
PR #325 did it partially. Finish the job here.
Fixes the issue from https://github.com/Granulate/gprofiler/issues/417.
I manually tested the new k8s DaemonSet and it works fine.
The pattern `--token[^=]` doesn't have any other matches :)
=> Pass --token, --service-name with = everywhere

gprofiler/metadata/system_metadata.py, gprofiler/profilers/java.py, tests/test_java.py
For extra verbosity, we'd like to collect AP log at all times.
=> java: Read and log AP log also upon successful operation

tests/containers/java/musl.Dockerfile
It seems like "java" was removed, I get:
"Error response from daemon: manifest for java:latest not found: manifest unknown: manifest unknown"
Also, heading to https://hub.docker.com/_/java redirects you to https://hub.docker.com/_/openjdk so I suppose that's the official successor.
=> tests: Use openjdk images repository instead of java

tests/conftest.py, tests/containers/native/change_comm.Dockerfile, tests/containers/native/native.c, tests/containers/native/thread_comm.Dockerfile, tests/test_perf.py
I liked writing them because they helped me grasp the current state of affairs.
An unrelated change - we no longer delete the application docker images, it's a
waste of time.
=> tests: Add perf tests on changing comms

gprofiler/profilers/java.py
Reduce minimal supported JDK 8 version and add JDK 13 support.
None.
Support more JDK versions.
Profiled Java applications of the specified JDK versions.
None.
=> Reduce minimal supported JDK 8 version, add JDK 13 support

gprofiler/profilers/java.py, tests/test_java.py
Move jvm version parsing to granulate-utils.
JvmVersion class and parse_jvm_version method are now moved to granulate-utils submodule.
=> Move jvm version parsing to granulate-utils

README.md, deploy/ansible/gprofiler_playbook.yml
```
$ ansible-playbook -i XXX deploy/ansible/gprofiler_playbook.yml  --key-file ~/.ssh/mykey.pem -u ubuntu --extra-vars "gprofiler_token='MYTOKEN'" --extra-vars "gprofiler_service='MYSERVICE'"
PLAY [Install gProfiler] **********************************************************************************************************************************************************************************
TASK [Gathering Facts] ************************************************************************************************************************************************************************************
ok: [XXX]
TASK [Check mandatory variables] ************************************************************************************************************************************************************ …
```
=> Add Ansible as an installation method

tests/utils.py
pytest doesn't give enough information here.
This affects flaky tests, for example https://github.com/Granulate/gprofiler/runs/8290755032?check_suite_focus=true
=> tests: Print unexpected result in assert message

gprofiler/profilers/dotnet.py, gprofiler/utils/speedscope.py
Here's how it looks:
```
1;loving_kilby;dotnet;Process64 Process(1) (1) Args: _[net];(Non-Activities)_[net];Threads_[net];Thread (1)_[net];Fibonacci!dotnet.Program.Main()_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net];Fibonacci!dotnet.Program.Fibonacci(int32)_[net] …
```
=> dotnet: Add _[net] frame suffix to all frames from dotnet-trace

gprofiler/metadata/system_metadata.py
Sample output on a Graviton server:
```
ubuntu@ip-xxx:~$ cat /proc/cpuinfo 
processor	: 0
BogoMIPS	: 166.66
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3
processor	: 1
BogoMIPS	: 166.66
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3
processor	: 2
BogoMIPS	: 166.66
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3
processor	: 3
BogoMIPS	: 166.66
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part …
```
=> metadata: get_cpu_flags(): Fix it on Aarch64

gprofiler/profilers/dotnet.py, gprofiler/profilers/java.py, gprofiler/profilers/perf.py, gprofiler/profilers/python.py, gprofiler/profilers/ruby.py, gprofiler/utils/process.py, tests/containers/java/Dockerfile, tests/test_java.py, tests/test_libpython.py, tests/utils.py
I added a helper `is_process_basename` which checks both the comm & argv[0], then fixed all relevant sites to use it.
**EDIT**: manual tests described ahead, but I also added automatic tests for it.
To test, I applied this diff:
```
diff --git a/tests/containers/java/Dockerfile b/tests/containers/java/Dockerfile
index c2e6a74..e6c802f 100644
--- a/tests/containers/java/Dockerfile
+++ b/tests/containers/java/Dockerfile
@@ -7,5 +7,6 @@ ADD Fibonacci.java /app
ADD MANIFEST.MF /app
RUN javac Fibonacci.java
RUN jar cvmf MANIFEST.MF Fibonacci.jar *.class
+RUN cp `which java` `which java`xxx
-CMD ["sh", "-c", "java -jar Fibonacci.jar; sleep 10000"]
+CMD ["bash", "-c", "exec -a java javaxxx -jar Fibonacci.jar; sleep 10000"]
```
Before this branch:
```
[2022-09-06 22:12:39,801] WARNING: …
```
=> Colaesce process basename checks & check argv[0] as well

gprofiler/metadata/application_identifiers.py, tests/test_appids.py
* Add `--ini-paste-logged` - 
```
--ini-paste                             load a paste.deploy config file containing uwsgi section
--ini-paste-logged                      load a paste.deploy config file containing uwsgi section (load loggers too)
```
* Support `.ini` because they can be passed just that way.
* Prevent `uwsgi: None` - instead `uwsgi: wsgi module not found`.
=> appids: uwsgi: Handle additional '.ini' options, and avoid "uwsgi: None" appid

gprofiler/profilers/java.py, gprofiler/profilers/python.py, gprofiler/profilers/ruby.py, gprofiler/utils/process.py
Java, Python, and Ruby profilers rely on searching /proc/PID/maps the same way, so refactored that to a function and replaced read_proc_file with the function from granulate-utils.
=> Use read_proc_file helper from granulate-utils

README.md, gprofiler/main.py, gprofiler/utils/proxy.py
Continues https://github.com/Granulate/gprofiler/pull/369 to provide more information for the users upon a connection error.
We use the same logic as `urllib` uses to extract the proxy.
=> Log HTTP proxy upon connection error

.github/workflows/build-container-and-test.yml, scripts/build_x86_64_container.sh
This is done by default now, to avoid confusion when running tests. Instead of requiring the user to pass this manually.
Closes: #492
=> scripts: build_x86_64_container.sh: Tag image to the name expected by tests

tests/conftest.py, tests/test_java.py, tests/test_sanity.py, tests/utils.py
dotnet_command_line & java_command_line are 2 fixtures that require java/dotnet to be installed, and if they're not installed, the fixture fails. By being eager - this fails the entire test suite. Now they're lazy so the lack of java/dotnet will fail only relevant tests.
Additionally, I made the fixture cached - to avoid re-compilation of the artifacts. This will be improved in the future by avoiding the build at all and copying the artifacts from the matching container.
Related: #481
=> tests: Turn command_line fixture lazy

dev-requirements.txt
Trying to solve https://github.com/Granulate/gprofiler/actions/runs/3173626903/jobs/5220214768.
I searched online for the error and got to this one: https://stackoverflow.com/a/73932581/ which matches what I suggested [here](https://github.com/Granulate/gprofiler/pull/517#issuecomment-1270023442). By upgrading flake8 I now see in its downloaded dependencies that it adds the necessary constraint: `Collecting importlib-metadata<4.3,>=1.1.0`.
=> lint: Upgrade flake8

tests/test_java.py, tests/test_sanity.py, tests/utils.py
Functions snapshot_one_profile and snapshot_one_collapse are replaced by snapshot_pid_profile and snapshot_one_collapse in test_java.py and test_sanity.py tests.
https://github.com/Granulate/gprofiler/issues/514
Run test_java and test_sanity
=> Use snapshot_pid function instead of snapshot_one in tests

tests/conftest.py
This PR is adding --no-dotnet flag to profiler_flags fixture to avoid using dotnet profiler while testing other profilers.
=> Add --no-dotnet flag to profiler flags fixture in tests

pyi.Dockerfile, scripts/libunwind_build.sh, scripts/prepare_machine-unknown-linux-musl.sh
Switch to libunwind-1.6.2
- Upgraded libunwind-1.5.0 (Nov 2020) to latest stable libunwind-1.6.2 (Dec, 2021)
- Replaced libunwind-1.5.0 with libunwind-1.6.2
- Removed patching with 831459ee96 commit due to the commit is already included in v1.6.2. 
- Enabled devtools-8 to use gcc 8.3.1 in Centos GProfiler Builder
None
To operate on the latest stable libunwind release 
- Successful `./scripts/build_x86_64_container.sh` execution
- Successful `./scripts/build_x86_64_executable.sh` execution
- Shall be checked in CI pipeline. Please trigger testing suite
- [N/A]  I have updated the relevant documentation. 
- [N/A] I have added tests for new logic.
=> Upgrade libunwind to latest stable version (v1.5.0 -> v1.6.2)

gprofiler/profilers/node.py
Instead of assigning `process.mainModule.require("fs")` to a const, now we call `readlinkSync("/proc/self/ns/pid")` directly.
This PR should fix problems with: 
`gprofiler.profilers.node: Could not create debug symbols for pid Reason: SyntaxError: Identifier 'fs' has already been declared` 
`Traceback (most recent call last):
File "gprofiler/profilers/node.py", line 129, in _execute_js_command
KeyError: 'value'`
=> Avoid using const multiple times for one variable in nodejs profiler

tests/test_sanity.py
Increasing duration of gprofiler container should avoid container stopping before application fibonacci starts.
https://github.com/Granulate/gprofiler/issues/513
I added artificial delay to `_application_process` function by using `time.wait(10)` and then I ran the test_sanity.py.
=> Increase duration of gprofiler container in test_from_container_spawned_process test

deploy/ecs/gprofiler_task_definition.json
After reading more on ECS task definitions, I understand the meaning of the values better.
* `cpu` is like k8s requests
* `memory` is like k8s limit
* `memoryReservation` is like k8s requests
* No need to specify both at task defintiion level and container level - I removed the task definition level.
The new values match the values we use for the k8s DaemonSet.
Some references:
* https://aws.amazon.com/blogs/containers/how-amazon-ecs-manages-cpu-and-memory-resources/
* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_limits
=> deploy: ecs: Update task definition resources

gprofiler/profilers/java.py
This data is not included when running the profiler in protocol v1, and we want it to, so for now the logs are a solution.
=> java: Add app metadata in gProfiler log for profile-api-version v1

gprofiler/utils/__init__.py
The purpose of this PR is to avoid checking if kernel threads are golang/node processes, hence adding https://github.com/Granulate/granulate-utils/pull/95.
Used `is_kernel_process` function.
Existing automatic tests only.
=> Updated granulate-utils version and used is_kernel_process function

gprofiler/profilers/node.py, tests/containers/nodejs/fibonacci.js
This PR:
- increases timeout to creating connection with debugger socket in NodeJS profiler.
- adds sleep in fibonacci.js application to lower CPU usage
https://github.com/Granulate/gprofiler/issues/538
NodeJS Tests are flaky.
=> Fix flaky NodeJS tests

gprofiler/profilers/node.py, tests/test_node.py
This PR removes experimental replMode (it is not needed in our case because we are not declaring any variables, and it seems to not work on NodeJS 14+). Also this PR adds closing socket after closing debugger.
https://github.com/Granulate/gprofiler/issues/550
Run test_nodejs_matrix
=> Fix using attach_maps on NodeJS 14+

gprofiler/profilers/java.py, scripts/async_profiler_build_shared.sh
This PR & the accompanying AP change fix this scenario:
* Java app is taking time to handle the attach request
* fdtransfer had a timeout of 10 seconds while jattach has a higher one (by default 30 but configurable with `--java-jattach-timeout`)
* by the time the app starts to handle the attach request, fdtransfer is already exited and AP gets this error:
```
gprofiler.profilers.java.JattachException: Command '['/app/gprofiler/resources/java/jattach', '837867', 'load', '/tmp/gprofiler_tmp/async-profiler-v2.8.3g5/glibc/libasyncProfiler.so', 'true', 'start,event=cpu,file=/tmp/gprofiler_tmp/tmpq5dgrqc1/async-profiler-837867.output,collapsed,ann,sig,interval=90909090,log=/tmp/gprofiler_tmp/tmpq5dgrqc1/async-profiler-837867.log,fdtransfer=@async-profiler-837867-6eb885285f6505442f90,safemode=64, …
```
=> java: Ensure fdtransfer lasts for as long as jattach timeout

gprofiler/profilers/perf.py
This PR sets stdout and stderr streams of perf process to non blocking.
https://github.com/Granulate/gprofiler/issues/612
Added `raise exception()` to try block in `wait_and_script()` -> on master - gProfiler stucks on reading from stdout and stderr (like in related issue), after these changes it reads the stream and continues
=> perf: Set stdout and stderr streams of perf process to non blocking

.github/workflows/build-container-and-deploy.yml, .github/workflows/build-container-and-test.yml, .github/workflows/build-executable-test-deploy.yml, .github/workflows/linters.yml, README.md, gprofiler/merge.py, gprofiler/profilers/perf.py, gprofiler/profilers/php.py, gprofiler/profilers/python_ebpf.py, gprofiler/profilers/registry.py, gprofiler/utils/__init__.py, mypy.ini, requirements.txt, setup.py, tests/test_executable.py
After https://github.com/Granulate/granulate-utils/pull/107 is merged.
Since https://github.com/Granulate/gprofiler/pull/597 we no longer need any 3.6, 3.7 support. Time to move forward
=> Drop support for Python 3.6, 3.7

Dockerfile, gprofiler/exceptions.py, gprofiler/log.py, gprofiler/main.py, gprofiler/metadata/application_identifiers_java.py, gprofiler/metadata/metadata_collector.py, gprofiler/metadata/system_metadata.py, gprofiler/state.py, pyi.Dockerfile, tests/conftest.py, tests/test_java.py
Closes: https://github.com/Granulate/gprofiler/issues/525
I didn't support this feature in A/B mode as suggested in the ticket, it's much changes than I expected and it'll be hard to maintain both infras in the code.
Some changes I did as part of it:
* state `run_id` and `cycle_id` are no longer added in logging level, then omitted in local logger - I add them in glogger level.
TODOs:
=> Use glogger as remote logging infra

gprofiler/profilers/perf.py, tests/test_node.py, tests/test_perf.py, tests/test_sanity.py
Restart perf once per 60 minutes to avoid memory leak from issue https://github.com/Granulate/gprofiler/issues/528.
https://github.com/Granulate/gprofiler/issues/528
Run gprofiler in continuous mode manually.
=> perf: Restart perf every 60 minutes if perf used memory exceeds 512 MB

gprofiler/main.py, gprofiler/metadata/metadata_collector.py
metadata_collector isn't used if --disable-metadata, but we need profiling_mode in all cases.
If you run with `--disable-metadata` without this branch, you'll get:
```
[2022-12-16 23:47:16,222] ERROR: gprofiler: Unexpected error occurred                                                                                                                         
Traceback (most recent call last):                                                                                                                                                            
File "/app/gprofiler/main.py", line 993, in main                                                                                                                                            
gprofiler.run_single() …
```
=> Add "profiling_mode" to metadata outside of metadata_collector

gprofiler/containers_client.py, gprofiler/profilers/perf.py, gprofiler/utils/perf.py
Fixes:
```
granulate-gprofiler  | [15:55:20] Could not get a container name for PID -1
granulate-gprofiler  | Traceback (most recent call last):
granulate-gprofiler  |   File "/app/gprofiler/containers_client.py", line 61, in _safely_get_process_container_name
granulate-gprofiler  |     container_id = get_process_container_id(Process(pid))
granulate-gprofiler  |   File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 326, in __init__
granulate-gprofiler  |     self._init(pid)
granulate-gprofiler  |   File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 335, in _init
granulate-gprofiler  |     raise ValueError('pid must be a positive integer (got %s)'
granulate-gprofiler  | ValueError: pid must be a positive integer (got -1)
```
=> Don't try getting container name for PIDs 0 / -1

gprofiler/utils/__init__.py
Fixes:
```
[2023-01-04 18:16:52,954] ERROR: gprofiler: Profiling run failed!
File "/app/gprofiler/main.py", line 361, in run_continuous
self._snapshot()
File "/app/gprofiler/main.py", line 327, in _snapshot
self._generate_output_files(merged_result, local_start_time, local_end_time)
File "/app/gprofiler/main.py", line 213, in _generate_output_files
run_process(
File "/app/gprofiler/utils/__init__.py", line 279, in run_process
raise reraise_exc
File "/app/gprofiler/utils/__init__.py", line 250, in run_process
stdout, stderr = process.communicate(timeout=0.001, **communicate_kwargs)
File "/usr/lib/python3.8/subprocess.py", line 1003, in communicate
raise ValueError("Cannot send input after starting communication")
ValueError: Cannot send input after …
```
=> utils: run_process(): Don't try writing stdin more than once

gprofiler/profilers/python.py
Fixes:
```
File "psutil/_pslinux.py", line 1576, in wrapper
File "psutil/_pslinux.py", line 1696, in cmdline
File "psutil/_common.py", line 725, in open_text
FileNotFoundError: [Errno 2] No such file or directory: '/proc/17961/cmdline'
During handling of the above exception, another exception occurred:
File "gprofiler/profilers/python.py", line 262, in _select_processes_to_profile
File "gprofiler/profilers/python.py", line 278, in _should_skip_process
File "psutil/__init__.py", line 677, in cmdline
File "psutil/_pslinux.py", line 1583, in wrapper
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=17961)
```
=> python: Add missing NoSuchProcess catch

gprofiler/exceptions.py
gProfiler gave me a super long log that killed my terminal, started with this:
<details>
<summary>Log</summary>
```
granulate-gprofiler  | [10:50:36] Running perf failed; consider running gProfiler with '--perf-mode disabled' to avoid using perf
granulate-gprofiler  | Traceback (most recent call last):
granulate-gprofiler  |   File "/app/gprofiler/main.py", line 292, in _snapshot
granulate-gprofiler  |     system_result = system_future.result()
granulate-gprofiler  |   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
granulate-gprofiler  |     return self.__get_result()
granulate-gprofiler  |   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
granulate-gprofiler  |     raise self._exception
granulate-gprofiler  |   File …
```
=> Truncate stdio in CalledProcessError

gprofiler/profilers/java.py
PROBE_SP was proven useful to get more accurate traces. This also removes reference from JAVA_STATE which is now named diffrently and has a different value, and we no longer want.
=> java: async-profiler: Default async-profiler safemode of PROBE_SP

scripts/async_profiler_build_shared.sh, tests/test_java.py
Removing local workaround for semicolons in frame names; upstream already handles this.
- Integrate with Granulate/async-profiler#4.
- Add test that verifies the java frames from async profiler include no semicolon `';'`.
#648 
- the less changes to upstream AP, the better.
Testcase added in `test_java.py` testsuite.
=> java-ap: remove semicolon patch

scripts/async_profiler_build_shared.sh, tests/containers/java/Fibonacci.java, tests/test_java.py
Make sure that async-profiler generates no output to profiled process stdout/ stderr streams.
#649 
We don't need any output from async-profiler to appear in profiled process output streams. We don't need it and want to avoid it.  
Recently few commits were merged which removed some print statements reaching process outputs.
Testcase was added to `test_java` testsuite.
=> Add test for zero stray output from java async-proviler

deploy/dataproc/gprofiler_initialization_action.sh
Tested using:
```sh
gsutil cp deploy/dataproc/gprofiler_initialization_action.sh gs://.../gprofiler_initialization_action.sh
export TOKEN='...'
export SERVICE='dataproc'
gcloud dataproc clusters create gprofiler-spark \
--initialization-actions gs://.../gprofiler_initialization_action.sh \
--metadata gprofiler-token="$TOKEN",gprofiler-service="$SERVICE",spark-metrics=1,enable-stdout="1" --region us-east1
```
with both `spark-metrics=1` and w/o. Works as expected; with it appends `--collect-spark-metrics` to command, without it does not.
=> dataproc: collect Spark metrics when spark-metrics attribute is 1

gprofiler/profilers/java.py
Fixes this stacktrace:
```
File "gprofiler/profilers/java.py", line 518, in _run_async_profiler
File "gprofiler/utils/__init__.py", line 283, in run_process
gprofiler.exceptions.CalledProcessError: Command ['/opt/granulate/gprofiler/_MEInirGjV/gprofiler/resources/java/jattach', '149163', 'load', '/tmp/gprofiler_tmp/async-profiler-v2.9g4/glibc/libasyncProfiler.so', 'true', 'start,event=cpu,file=/tmp/gprofiler_tmp/tmpyevcrgni/async-profiler-149163.output,collapsed,ann,sig,interval=90909090,log=/tmp/gprofiler_tmp/tmpyevcrgni/async-profiler-149163.log,fdtransfer=@async-profiler-149163-35b4584d1aa63cffe42e,safemode=127,timeout=90'] returned non-zero exit status 1.
stdout: b'Connected to remote JVM
'
stderr: b'Unexpected EOF reading response
'
During handling …
```
=> java: Gracefully handle exited Java process upon JattachException

gprofiler/main.py, gprofiler/profiler_state.py, gprofiler/profilers/dotnet.py, gprofiler/profilers/factory.py, gprofiler/profilers/java.py, gprofiler/profilers/perf.py, gprofiler/profilers/php.py, gprofiler/profilers/profiler_base.py, gprofiler/profilers/python.py, gprofiler/profilers/python_ebpf.py, gprofiler/profilers/ruby.py, tests/conftest.py, tests/test_java.py, tests/test_node.py, tests/test_perf.py, tests/test_python.py, tests/test_sanity.py, tests/utils.py
Refactor code to make any future changes in profilers parameters easier. Created another object that keeps "state parameters" for profilers.
As mentioned in https://github.com/Granulate/gprofiler/pull/667,
=> Refactor profiler state parameters to separate object

README.md
Clarify for the users that SYS_PTRACE is not optional, and which runtimes actually require it.
=> docs: Clarify SYS_PTRACE need on Fargate installations

gprofiler/spark/spark_collector.py
Applications metrics is their current form result in too high metrics cardinality. Disabling them for now until we improve it.
=> Disabled spark_collector applications metrics by default

gprofiler/client.py
Send the hostname in `X-GProfiler-Hostname` header.
Ran on EMR with `--curlify-requests`. Verified header is present with correct value.
=> spark: Send hostname header

.github/workflows/build-executable-test-deploy.yml, README.md, gprofiler/profilers/dotnet.py, gprofiler/profilers/python.py, gprofiler/profilers/ruby.py, gprofiler/utils/__init__.py
Alpine grep doesn't support flag -P (Perl compatible regular expressions), so pgrep_map method now uses -E (Extended regular expressions)
https://github.com/Granulate/gprofiler/issues/636
=> Enable running gprofiler executable on Alpine

gprofiler/client.py, gprofiler/metrics/__init__.py, gprofiler/spark/spark_collector.py
Currently samples are only generated once per metric name, ignoring additional labels which might result in additional series. This PR standardizes the data classes to be used for samples and the entire snapshot, and fixes the code to report samples for all series even if they have the same metric name but different labels.
=> metrics: Send samples per series instead of per metric name

gprofiler/profilers/java.py
Needs https://github.com/Granulate/granulate-utils/pull/133
I tested manually the different versions & expected result of `_is_zing_vm_supported` - works fine.
=> java: Guard from enabling async-profiler over Zing ZVM-17168

gprofiler/profilers/java.py
See related async-profiler ticket which explains further: https://github.com/async-profiler/async-profiler/pull/717
See the comment on `needs_musl_ap_cached()` for an explanation on this PR.
I'm not adding an automatic test now because async-profiler currently fails running on the image I used to test it, anyway. The glibc build requires libstdc++ (unlike the musl build) but the image has musl and glibc-compat but NO libstdc++. At the very least, we don't crash glibc-compat processes anymore :shrug: which is what happens before this PR. That's a start...
I'm not sure I plan to support a glibc build with static libstdc++ (for this case) because async-profiler might, in the near future, be libc agnostic, and then we have to restructure the code here anyway. My goal with this PR now is to …
=> java: Use glibc build of async-profiler for glibc-compat processes

gprofiler/client.py, gprofiler/utils/__init__.py
~The existing `get_iso8601_format_time` cannot be changed because the server might not support Z-suffixed timestamps, which we've agreed to use for the spark metrics :/~
Agreed to send in long format.
=> metrics: send time as ISO8601

gprofiler/exceptions.py, gprofiler/profilers/java.py, gprofiler/profilers/python.py, gprofiler/profilers/python_ebpf.py, gprofiler/utils/__init__.py, gprofiler/utils/perf.py
I looked at this area because I saw multiple errors like:
```
[2023-03-28 16:32:39,730] CRITICAL: gprofiler: Running perf failed; consider running gProfiler with '--perf-mode disabled' to avoid using perf
[2023-03-28 16:32:39,731] ERROR: gprofiler: Profiling run failed!
File "gprofiler/main.py", line 378, in run_continuous
File "gprofiler/main.py", line 310, in _snapshot
File "concurrent/futures/_base.py", line 458, in result
File "concurrent/futures/_base.py", line 403, in __get_result
File "concurrent/futures/thread.py", line 58, in run
File "gprofiler/profilers/perf.py", line 483, in snapshot
File "gprofiler/profilers/perf.py", line 322, in wait_and_script
File "gprofiler/utils/__init__.py", line 284, in run_process …
```
=> utils: process exceptions: Strict type checks

gprofiler/gprofiler_types.py, gprofiler/main.py, gprofiler/profiler_state.py, gprofiler/profilers/perf.py, gprofiler/profilers/php.py, gprofiler/profilers/profiler_base.py, gprofiler/profilers/python_ebpf.py, gprofiler/utils/__init__.py, tests/conftest.py, tests/test_sanity.py
This PR:
- Add flag --pid that enables providing chosen pids to profile
- Checks if at least one of processes provided is alive
- pids are passed to profilers via ProfilerState
- Adds test for checking if only provided pid is profiled with async-profiler
https://github.com/Granulate/gprofiler/issues/605
=> Filter PIDs to profile

tests/conftest.py, tests/test_executable.py
=> aarch64 executable tests

gprofiler/client.py, gprofiler/log.py, gprofiler/main.py
In certain non-SaaS deployments we'd like to run the server in HTTPS but with (possibly) dummy or self-signed certificates. This PR adds a simle option like curl's `--insecure`, wget's `--no-check-certificate` etc.
Tested by -
1. running a "simple HTTPS server" with self signed certificate per [this link](https://gist.github.com/dergachev/7028596?permalink_comment_id=4476598#gistcomment-4476598)
2. Testing with curl - without `-k` I get `curl: (60) SSL certificate problem: self-signed certificate`, with `-k` the connection is established.
3. Testing with gprofiler w/o this PR - getting `SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')` for the `get_health` check.
4. Testing with gprofiler with this PR …
=> Add --no-verify option to disable server certificate verification

dev-requirements.txt, gprofiler/gprofiler_types.py, requirements.txt, tests/conftest.py, tests/test_app_metadata.py, tests/test_java.py
This is incremental work towards the full https://github.com/Granulate/gprofiler/pull/769, starting with some of the dev packages, fixes by new versions of formatters, etc
=> Upgrade dev Python packages, part 1

gprofiler/profilers/python.py, tests/test_executable.py
See https://github.com/Granulate/gprofiler/pull/772#issuecomment-1510183814
=> python: Prevent implicit fallback to py-spy if pyperf is explicitly requested

gprofiler/profilers/java.py
=> java: Add JDK 19 to min supported versions

tests/conftest.py
In test titles instead of f.e.:
```
tests/test_node.py::test_nodejs_attach_maps[False-command_line0-without-flags-nodejs-attach-maps]
tests/test_node.py::test_nodejs_attach_maps_from_container[True-command_line0-without-flags-nodejs-attach-maps]
```
we will have
```
tests/test_node.py::test_nodejs_attach_maps[on_host-command_line0-without-flags-nodejs-attach-maps]
tests/test_node.py::test_nodejs_attach_maps_from_container[in_container-command_line0-without-flags-nodejs-attach-maps]
```
https://github.com/Granulate/gprofiler/issues/536
=> Add ids to in_container fixture

scripts/pyperf_build.sh, tests/test_python.py
Update PyPerf to support Python 3.11.
Adopting changes implemented in [Granulate/bcc#45](https://github.com/Granulate/bcc/pull/45).
#727 
Need to support latest versions of Python.
Enabled Python-3.11 configuration as a target for python tests.
=> Upgrade PyPerf to support Python 3.11

pyi.Dockerfile
CPython uses glibc's `getaddrinfo()` to resolve hostnames. glibc tries to dynamically load the backend libs that implement the actual resolution, `libnss_files.so` and `libnss_dns.so` (as configured by staticx), which are unfortunately missing. When running staticx, it determines the libs to include by examining dependencies using `ldd`. For this reason, staticx adds a "fake" dependency on these two libs by linking `libnssfix` -- staticx's injected lib to configure nss to use only `files` and `dns` backends and ignore system configuration -- with `nss_files` and `nss_dns`. When building for ARM, we recompile staticx v0.13.6 with a patch that fixes some other static NSS issues (resolved in v0.13.7+) instead of using the prebuilt version from pypi.
The nss libs were never intended to be …
=> Fix getaddrinfo() EBUSY on ARM

.gitmodules, README.md, tests/conftest.py, tests/containers/golang/Dockerfile, tests/test_app_metadata.py, tests/test_java.py, tests/utils.py
Use golang binary identification brought to granulate-utils with PR https://github.com/Granulate/granulate-utils/pull/179.
With new mechanism in granulate-utils it's now possible to identify golang binary looking only at ELF sections. This PR is adopting this mechanism.
#817 
Added new testcase for a stripped golang binary, proving identification of golang programs is possible.
=> Use and test golang binary identification

README.md, gprofiler/profilers/perf.py
"smart" mode is more expensive memory & cpu wise due to running two perfs. Let's make it opt-in and not opt-out.
=> perf: Use "fp" mode by default

gprofiler/profilers/java.py, tests/test_java.py
https://github.com/Granulate/gprofiler/issues/675
Some java processes can be started from a binary that doesn't start with java. We want to support profiling them and provide full metadata including java version.
=> Support extracting java version for non-java named processes

.github/workflows/build-test-deploy.yml, scripts/build_aarch64_container.sh, scripts/build_x86_64_container.sh, scripts/build_x86_64_executable.sh
1. to standardize - as some locations used `docker buildx` and some used `DOCKER_BUILDKIT`
2. In https://github.com/Granulate/gprofiler/actions/runs/5956037826/job/16158530773 it seems that `DOCKER_BUILDKIT=1` fails although in the same workflow `docker buildx` worked 🤷
=> Use BuildKit via "docker buildx" everywhere

scripts/build_node_package.sh
node-gyp 10.x.x was released recently, and our build started failing with this error:
16.93 gyp ERR! configure error
16.93 gyp ERR! stack TypeError: Cannot read property 'pipeline' of undefined
Pinning to 9.x.x helps.
I saw it asked online - https://stackoverflow.com/questions/77401392/unable-to-install-node-using-nvm - but no response so far 🤷
=> build: node: Pin node-gyp==^9.4.1

gprofiler/__init__.py, gprofiler/log.py
It's nicer when `gprofiler:` is always included, and generally it's nicer to have the same format for file / stdout.
=> log: Use the same format when we're in INFO / DEBUG mode

gprofiler/profilers/java.py, tests/conftest.py, tests/test_java.py, tests/utils.py
Fixes a regression from https://github.com/Granulate/gprofiler/commit/6360449252793ad59802a3c09fde297646529b7d, and improves the tests
so we'd catch it next time :)
=> java: Fix regression _find_rw_exec_dir() failing to handle ro dirs

gprofiler/profilers/java.py
Tested on `openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Corretto-21.0.1.12.1 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Corretto-21.0.1.12.1 (build 21.0.1+12-LTS, mixed mode, sharing)`.
=> java: Add min JDK 21 version

scripts/prepare_machine-unknown-linux-musl.sh
As usual, zlib is upgraded and the old version is removed from the server. The best way to have your users pull security fixes
=> build: Upgrade to zlib 1.3.1

scripts/openssl_build.sh
compiling `python3.10` vs. newer OpenSSL version.
here, we use the same OpenSSL version [this docker image](https://hub.docker.com/layers/library/python/3.10.13/images/sha256-d5b1fbbc00fd3b55620a9314222498bebf09c4bf606425bf464709ed6a79f202) shipped it's `python3.10` with.
```
$ docker run --name "python_cont" -it python:3.10.13@sha256:d5b1fbbc00fd3b55620a9314222498bebf09c4bf606425bf464709ed6a79f202 bash
root@d671d3134763:/# python --version
Python 3.10.13
root@d671d3134763:/# python -c 'import ssl; print(ssl.OPENSSL_VERSION)'
OpenSSL 3.0.11 19 Sep 2023
root@d671d3134763:/#
```
=> scripts/openssl_build.sh: OpenSSL v3.0.11

gprofiler/profilers/java.py
=> profilers/java.py: using `/dev` as last resort to store AP dso

.github/workflows/build-test-deploy.yml
GH have deprecated `actions/upload-artifact: v2` and `actions/download-artifact: v2` ([further reading](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/))
This makes our CI to fail. [see here](https://github.com/Granulate/gprofiler/actions/runs/10885795220/job/30204253014?pr=921#step:1:36)
=> CI: use actions/upload-artifact@v4 and actions/download-artifact@v4

.github/workflows/build-test-deploy.yml, gprofiler/utils/__init__.py
https://github.com/Granulate/gprofiler/pull/921#discussion_r1743316860
=> bugfix: `start_process` ensuring passing of `TMPDIR` when needed

gprofiler/profilers/python_ebpf.py, gprofiler/utils/__init__.py
cleanup each instance of PyPerf staticx directories on termination.
We experienced where there were a-lot of staticx tempdirs leftovers.
=> profilers/python_ebpf.py: specifying newly TMPDIR on each instance of PyPerf

gprofiler/gprofiler_types.py, gprofiler/profilers/python.py, tests/test_python.py, tests/test_sanity.py
Expose py-spy specific flag that forces gProfiler to profile given processes.
=> PythonProfiler: expose `--python-pyspy-process`

gprofiler/main.py, gprofiler/platform.py, gprofiler/system_metrics.py
Added an option to gprofiler CLI to use perfspect HW metrics collection and provide the path to it
(1) Added option "--perfspect-path" to gprofiler CLI.
Without path collection of HW metrics will not start.
(2) Disabled this option not on linux and on aarch64
(3) Fixed Python linter issues
Tested locally with and without option provided:
> sudo ./build/x86_64/gprofiler --perfspect-path ~/.../perfspect/perfspect -o ~/.../gprofiler_results/
Checked .col files after collection:
metrics field in file header with option -
` "metrics": {"cpu_avg": 0.1, "mem_avg": 2.9153846153846152, "cpu_freq": 1.102548528, "cpu_cpi": 2.3034023, "cpu_tma_fe_bound": 40.3853196, "cpu_tma_be_bound": 44.372709, "cpu_tma_bad_spec": 5.5948107, "cpu_tma_retiring": 9.64716058},`
without option -
`"metrics": {"cpu_avg": …
=> Added an option to gprofiler CLI to use perfspect HW metrics collection and provide the path to it

executable.Dockerfile, requirements.txt, scripts/build_x86_64_executable.sh, scripts/prepare_machine-unknown-linux-musl.sh
This is to provide the workaround for pip install failure due to proxy. 
The error signature related to the proxy issue is 
_Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))) - skipping_
To workaround the issue, we need to ignore SSL errors by setting [pypi.org](https://pypi.org/) and [files.pythonhosted.org](https://files.pythonhosted.org/) as well as the older [pypi.python.org](https://pypi.python.org/) as trusted hosts.
I explored the alternative workaround using the pip config but …
=> Support build on vpn network with proxy

gprofiler/hw_metrics.py, gprofiler/main.py, gprofiler/merge.py, gprofiler/platform.py, tests/test_merge.py
This is the new feature supporting HW metrics in gprofiler that is collected via Perfspect tool.
The feature is requested at https://github.com/intel/gprofiler/issues/956. The gprofiler metadata section includes the HW metrics for both text and the HTML content as blob generated by Perfspect tool.
=> Initial POC for perfspect integration

.github/workflows/codeql.yml
Changes the CodeQL workflow triggers to enable manual running and limit push triggers only to master branch.
This is working for gProfiler Performance Studio repo, want to use it here too.
=> Update CodeQL workflow triggers

scripts/build_aarch64_executable.sh, scripts/build_x86_64_executable.sh, scripts/dotnet_prepare_dependencies.sh, tests/containers/dotnet/Dockerfile
Attempt to upgrade .net sdk version to get rid of CVE-2023-36049
=> Upgrade .net version

gprofiler/profilers/java.py, gprofiler/utils/fs.py
This patch resolves #957. It removes the root ownership checks when the sudoless profiling is requested.
=> Support java profiling without root privilege in a container
