- gprofiler/python.py
The "pid" variable was just bound to the last value from the iteration on pids_to_profile.
The error message displayed an incorrect PID.
Running the tests + ran the profiler locally and verified that error logs now contain the real PID.
Prior to this fix, when profiling failed for whatever reason, we'd get:
```
[2021-03-14 12:05:07,661] ERROR: gprofiler.python: Failed to profile Python process 2622561
...
gprofiler.exceptions.CalledProcessError: Command '['/app/gprofiler/resources/python/py-spy', 'record', '-r', '10', '-d', '60', '--nonblocking', '--format', 'raw', '-F', '--gil', '--output', '/tmp/gprofiler/tmpi7y06z60/1742.py.col.dat', '-p', '1742']' returned non-zero exit status 1. stderr: b'Error: Failed to parse python binary\nReason: No such file or …
```
> python: Use the real erroneous PID when printing failure message

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .gitignore
- README.md
- cmp_tags.sh
- dev-requirements.txt
- enable_hook.sh
- gprofiler/java.py
- gprofiler/utils.py
- pyi.Dockerfile
- pyi_build.py
- pyinstaller.spec
- tests/conftest.py
- tests/test_executable.py
- tests/test_python.py
- tests/test_sanity.py
- tests/util.py
gProfiler bundled to one executable using `Pyinstaller`, here are several main points:
- The build is on to of `Centos 7` docker image to support a wide range of machines.
- `GH actions` added which are build, test and deploy the executable to GH releases.
Bundle to one executable will extend the deployment options of gProfiler
and allow simple and frictionless deployment in more environments.
`Pytest` test added and works as follows:
- Receive the executable path (or generate the executable if path not supplied)
- Receive docker image name  to simulate different environments (if not passed will run on host)
- Run Java and Python test apps dockerized and on host (similar to all other tests)
The code shouldn't affect anyway the gProfiler code
> Bundle gProfiler to one executable

- .github/workflows/build.yml
Trigger build CI on git tag push
Build docker image and executable on release, so latest version of docker image and executable will be consistent with repository
> Trigger build CI on tags

- gprofiler/java.py
Adds support for profiling of Java processes that are run using [jsvc](https://commons.apache.org/proper/commons-daemon/jsvc.html).
Users who are using jsvc and would like to use gprofiler.
Tested on a Java application that I ran using jsvc.
> Added support for profiling of java processes that are run using jsvc

- README.md
- deploy/k8s/gprofiler.yaml
Add a basic template YAML for k8s deployment of gProfiler.
Allow deploying gProfiler easily over k8s.
On my local k8s cluster.
> deploy: Add k8s YAML

- gprofiler/java.py
We avoided running "jattach" again, but we still try to access files
via /proc/pid/root, which will fail.
Avoids these errors:
```
[2021-04-25 23:53:00,523] ERROR: gprofiler.java: Failed to profile Java process 194511
File "/app/gprofiler/java.py", line 227, in snapshot
result = future.result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
return self.__get_result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
raise self._exception
File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/app/gprofiler/java.py", line 148, in profile_process
return self._profile_process_with_dir(process, storage_dir_host, process_root)
File …
```
> java: Be graceful if process dies during profiling

- gprofiler/utils.py
Lets you know by the logs - how was gProfiler executed?
Ease debugging.
Locally (container + standalone executable)
> Log the run mode (container / k8s container / ...)

- gprofiler/utils.py
- lint.sh
Before:
```
ModuleNotFoundError: No module named 'gprofiler.resources.python.pyperf'
```
After:
```
Exception: Resource 'python/pyperf/PyPerf' not found!
```
> Report clearer message when a resource is missing

- gprofiler/main.py
Allows running with `-o` to get collapsed stack files, if I don't want the flamegraphs generated for each of them.
I want to run gProfiler, collecting collapsed stack files but I don't need the flamegraph for each.
* Without any flag - flamegraph is generated.
* With `--flamegraph` - flamegraph is generated.
* With `--no-flamegraph` - flamegraph is not generated.
> Allow skipping flamegraph generation with --no-flamegraph

- gprofiler/main.py
Automatically create the output directory if it doesn't exist.
Nicer user experience.
* Tested existing output directory
* Tested output directory is a file
* Tested a component in its path is a file
> Create output directory if it doesn't exist

- README.md
- gprofiler/main.py
To avoid bias from recurring events/routines.
Improve sampling results.
Our tests.
> Change default frequency to 11

- scripts/pyspy_build.sh
Use new py-spy version which adds Python-specific suffixes
> Bump py-spy to v0.3.7g2

- gprofiler/main.py
Log the commandline gProfiler was executed with.
Helps the reader of the logs understand the exact settings gProfiler is run with.
Tested locally (both container & standalone executable) and verified the output appears as I expect it to.
```
[2021-06-05 22:04:20,441] INFO: gprofiler: Running gprofiler (version 1.1.0): -o /tmp/output --token <....> --service-name blabla -d 60 -v -c --no-python --no-php
```
> Log command line of execution

- dev-requirements.txt
Always a good thing to do. Also, a recent upgrade in mypy now fails our tests :sweat:
> Pin test requirements

- gprofiler/java.py
- gprofiler/merge.py
- gprofiler/perf.py
- gprofiler/php.py
- gprofiler/profiler_base.py
- gprofiler/python.py
- gprofiler/ruby.py
- gprofiler/types.py
- gprofiler/utils.py
Merge reusable logic into `ProfilerBase`.
Improving the codebase.
CI
> Extract ProfilerInterface from ProfilerBase, and put more logic in the latter

- gprofiler/main.py
Skipping the check allows running gProfiler in a container, if a user wants to do it for whatever reason.
Allow running gProfiler in a container.
Without passing this flag, we get:
```
Please run me in the init PID namespace! In Docker, make sure you pass '--pid=host'. In Kubernetes, add 'hostPID: true' in the Pod spec.
You can disable this check with --disable-pidns-check
```
If passing this flag (and `--perf-mode none`) - gProfiler works :)
> Allow disabling the init PID NS check

- scripts/rbspy_build.sh
> Update rbspy fork (0.7.0)

- README.md
- images/studio.gif
Remove studio image from git lfs, add as user image.
Decrease LFS data throughput.
> Remove gif from lfs, add gif as user images

- scripts/pyperf_build.sh
After https://github.com/Granulate/bcc/pull/26 is merged
> Upgrade PyPerf

- deploy/docker-compose/docker-compose.yml
> Add a docker-compose template file

- scripts/pyspy_build.sh
Mainly to include https://github.com/benfred/py-spy/pull/428
Line numbers
CI
> Upgrade py-spy to 0.3.9

- README.md
Title says it all.
Based on https://github.com/Granulate/gprofiler/pull/174
> Add AWS Fargate running instructions

- README.md
- deploy/dataflow/setup.py
- mypy.ini
Added support for Dataflow installation. **PLEASE NOTE** -  it's currently only supported on Python pipelines.
> Add a Google Dataflow installation module

- scripts/rbspy_build.sh
New rbspy supports more ruby versions.
> Update rbspy to 0.8.1

- gprofiler/__init__.py
> Version 1.2.5

- gprofiler/utils.py
This utility function finds the "topmost ancestor" of a given PID,
such that the ancestor runs in the same mount namespace of the given PID.
I plan to use this function in a number of different PRs, hence adding it first here so they don't block each other.
```
$ docker top determined_dirac
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                55720               55697               0                   00:47               pts/0               00:00:00            sh
root                55778               55720               0                   00:47               pts/0               00:00:00            sleep 55555
```
then:
```
In [12]: get_mnt_ns_ancestor(Process(55778)) …
```
> utils: Add get_mnt_ns_ancestor()

- gprofiler/main.py
In perf-less mode, if we don't find any runtime profilers to run, we don't perform any snapshots,
and nothing waits between iterations.
This change will make sure we do wait.
Fixes this bug :)
Ran `master` in `--perf-mode disabled` and no runtime profilers. It loops indefinitely w/o waiting for the duration.
Ran this branch with the same settings - it correctly waits :)
> Always wait for at least "duration" between profiling sessions

- gprofiler/profilers/java.py
Access files of the process' mount NS via its topmost ancestor.
Based on https://github.com/Granulate/gprofiler/pull/203.
Avoid leaking output/log files should the process go down during profiling.
* CI
* I profiling a Java process and killed it with `pkill java`. On `master`, the temporary files of async-profiler remain on disk. On this branch, they don't.
> java: Clean files via topmost ancestor's root instead of process root

- gprofiler/main.py
Emit a log message upon successfully uploading my logs.
Helps debugging in hindsight - why logs arrived or haven't arrived.
Verified the message is indeed written upon success.
> Emit a log message upon successfully uploading my logs

- gprofiler/profilers/java.py
- requirements.txt
- tests/containers/java/Dockerfile
- tests/test_java.py
- tests/test_sanity.py
Enhanced the current java version check mechanism to parse the output of `java -version` and compare it against known "good" versions
Added new tests
> Added java version parsing and enhanced version checks

- .github/workflows/release.yml
- gprofiler/__init__.py
- gprofiler/profilers/java.py
After:
* https://github.com/Granulate/gprofiler/pull/212
* https://github.com/Granulate/gprofiler/pull/213
> gProfiler 1.2.7

- .github/workflows/release.yml
- gprofiler/__init__.py
- tests/test_executable.py
Waiting for:
* https://github.com/Granulate/gprofiler/pull/208
* https://github.com/Granulate/gprofiler/pull/219
> gProfiler 1.2.8

- gprofiler/profilers/java.py
> Use Hotspot helpers from utils

- gprofiler/__init__.py
After:
* https://github.com/Granulate/gprofiler/pull/235
> gProfiler 1.2.9

- deploy/k8s/helm-charts/.helmignore
- deploy/k8s/helm-charts/Chart.yaml
- deploy/k8s/helm-charts/templates/_helpers.tpl
- deploy/k8s/helm-charts/templates/daemonset.yaml
- deploy/k8s/helm-charts/values.yaml
Introduce helm-chart to deploy granulate DaemonSet
Add the helm-chart folder
For users who use helm
> add helm-chart

- README.md
- deploy/k8s/helm-charts/Chart.yaml
- deploy/k8s/helm-charts/templates/daemonset.yaml
- deploy/k8s/helm-charts/values.yaml
Several improvements to our Helm Chart installation:
1. Added installation instructions to Helm chart on README.md.
2. Added `extraArguments` to helm values so you can pass additional parameters
3. Updated mounts to match v1.2.10 requirements.
Tested manually on a local Kubernetes cluster (version v1.21):
1. Tested helm install and uninstall
2. Tested passing of additional arguments
> Further improvement to Helm chart and added installation instructions to README.md

- gprofiler/utils.py
> terminate child process on gprofiler death

- .github/workflows/build-container-and-test.yml
- gprofiler/kernel_messages.py
- gprofiler/profilers/java.py
- mypy.ini
- tests/conftest.py
- tests/test_executable.py
- tests/test_java.py
- tests/test_libpython.py
- tests/test_sanity.py
* Upgrade granulate-utils to a commit containing https://github.com/Granulate/granulate-utils/pull/19, which now makes it typed.
* Fix type errors stemming from this ^^
* Enable type checking on multiple other packages, and add a comment on all packages left that are still ignored.
CI
> mypy: Check types of more packages

- gprofiler/profilers/java.py
* Move function to granulate-utils, see https://github.com/Granulate/granulate-utils/pull/21
* Move `java_exit_code_to_signo()` to granulate-utils, see https://github.com/Granulate/granulate-utils/pull/22
> java: Move some logic to granulate-utils

- gprofiler/profilers/java.py
It's easier to read & understand when the info is augmented inside the exception itself.
Still thinking how we can automate this into a test.
CC @YoniKF
> java: Add the "AP DSO was loaded" into JattachException

- gprofiler/profilers/java.py
Move logic to granulate-utils, see https://github.com/Granulate/granulate-utils/pull/26
> Move proc_events run_in_ns to granulate-utils

- gprofiler/docker_client.py
Move `get_process_container_id` to granulate-utils - see https://github.com/Granulate/granulate-utils/pull/25
> docker_client: Move get_process_container_id to granulate-utils

- gprofiler/profilers/java.py
- gprofiler/utils/fs.py
> java: Simplify complexity of atomic copies by ensuring sync

- tests/test_java.py
As fixed in https://github.com/Granulate/gprofiler/pull/313
> tests: java: Add test for deleted libjvm.so

- gprofiler/__init__.py
- gprofiler/metadata/application_identifiers.py
Stripped arguments from Java app id
> Stripped arguments from Java app id

- gprofiler/__init__.py
- gprofiler/main.py
- gprofiler/metadata/application_identifiers.py
- gprofiler/metadata/enrichment.py
Bumped version to v1.2.19 + imports reordering
> Bumped version to v1.2.19 + imports reordering

- lint.sh
Title.
See https://github.com/Granulate/gprofiler/pull/334#pullrequestreview-929610984
> ci: Fail if isort modifies any files

- gprofiler/main.py
v1 server did not have the logs endpoint, so don't try sending them.
> Don't upload logs if profile API version is v1

- gprofiler/kernel_messages.py
- gprofiler/profilers/java.py
Improve log messages about failing, optional features (per https://github.com/Granulate/gprofiler/issues/327#issuecomment-1086753316)
> Improve warning log messages about failing optional features

- dev-requirements.txt
- gprofiler/log.py
- requirements.txt
Upgrade mypy version from 0.901 to 0.942, bumping granulate-utils to a version with the same change.
> Upgrade mypy to 0.942

- gprofiler/utils/fs.py
> utils: fs: is_rw_exec_dir(): suppress_log=True

- .github/workflows/build-container-and-deploy.yml
- .github/workflows/build-executable-test-deploy.yml
- gprofiler/__init__.py
- scripts/setup_runner_requirements.sh
Wonder if there's a better way to test it than creating new releases :sweat_smile:
> ci: Fixes for new release workflows

- .github/workflows/build-container-and-deploy.yml
Solves this https://github.com/Granulate/gprofiler/runs/6256320311?check_suite_focus=true
> ci: Run verify_tag.sh before "Push manifest" - this exports needed vars

- .github/workflows/linters.yml
- .hadolint.yaml
- Dockerfile
- dockerfile_lint.sh
- lint.sh
- pyi.Dockerfile
- scripts/bcc_helpers_build.sh
- scripts/build_aarch64_executable.sh
- scripts/build_x86_64_executable.sh
- scripts/phpspy_build.sh
- scripts/phpspy_env.sh
- scripts/pyperf_build.sh
- shell_lint.sh
I encountered hadolint and wanted to try it out. Also a good excuse to try out shellcheck (although I haven't completed the work there yet, so it's not enabled in CI).
It's always good to have more linters.
> Add hadolint (Dockerfiles linter) and begin work on shellcheck

- gprofiler/gprofiler_types.py
- gprofiler/profilers/java.py
- scripts/async_profiler_build_shared.sh
- scripts/async_profiler_env_glibc.sh
- scripts/async_profiler_env_musl.sh
- tests/test_java.py
- tests/utils.py
> Upgrade async-profiler to v2.8

- gprofiler/profilers/java.py
- gprofiler/profilers/perf.py
- gprofiler/utils/process.py
- tests/conftest.py
- tests/containers/golang/Dockerfile
- tests/containers/golang/fibonacci.go
- tests/test_app_metadata.py
- tests/test_java.py
Collect the following metadata for golang processes:
* golang runtime version
* whether the binary is statically linked
* if not - whether it was linked with glibc or musl (currently assume these are the only 2 possibilities)
I added a test case to `test_app_metadata`
> Add metadata for golang processes

- gprofiler/metadata/application_metadata.py
- gprofiler/profilers/perf.py
- gprofiler/profilers/ruby.py
- tests/conftest.py
- tests/containers/nodejs/Dockerfile
- tests/test_app_metadata.py
Adding NodeJS app metadata
#389 
#389 
Having the CI test it for me, of course.
> Node perf metadata

- gprofiler/profilers/profiler_base.py
> Avoid double duration wait in SpawningProcessProfilerBase

- gprofiler/__init__.py
After ~~https://github.com/Granulate/gprofiler/pull/403~~ https://github.com/Granulate/gprofiler/pull/408
> gProfiler 1.3.0

- gprofiler/__init__.py
> gProfiler 1.4.0

- gprofiler/metadata/application_identifiers.py
- gprofiler/profilers/java.py
- tests/conftest.py
- tests/utils.py
Added collection of spark application name as an appid.
> Spark app name identifier collector

- gprofiler/metadata/application_metadata.py
- gprofiler/profilers/java.py
- gprofiler/profilers/python.py
- gprofiler/profilers/ruby.py
Pending merge of https://github.com/Granulate/granulate-utils/pull/59
> Upgrade granulate-utils

- gprofiler/log.py
> Send gProfiler version in log records

- gprofiler/utils/speedscope.py
PoC for https://github.com/Granulate/gprofiler/pull/412
> Add PoC speedscope -> collapsed converter

- gprofiler/__init__.py
After https://github.com/Granulate/gprofiler/pull/453
> gProfiler 1.6.0

- tests/test_app_metadata.py
> tests: app metadata: Add dotnet

- gprofiler/metadata/system_metadata.py
In preparation for https://github.com/Granulate/gprofiler/issues/382
> metadata: Send platform.system()

- Dockerfile
- README.md
- gprofiler/profilers/dotnet.py
- pyi.Dockerfile
- scripts/build_aarch64_container.sh
- scripts/build_aarch64_executable.sh
- scripts/build_x86_64_executable.sh
- scripts/dotnet_prepare_dependencies.sh
It just worked :shrug: so why not.
> dotnet: Support Aarch64

- README.md
- gprofiler/profilers/perf.py
> perf: Default to 'smart' mode

- gprofiler/metadata/application_metadata.py
- gprofiler/profilers/python.py
> python: Get Python version in app metadata for uwsgi apps

- scripts/perf_build.sh
- tests/test_perf.py
Changed commit of perf dependency in use.
#431
> Update gprofiler to improve fork handling

- tests/conftest.py
> tests: Build images lazily

- scripts/pyperf_build.sh
> PyPerf demangling c++ symbols - module update

- .github/workflows/linters.yml
- CONTRIBUTING.md
- scripts/async_profiler_build_glibc.sh
- scripts/async_profiler_build_shared.sh
- scripts/async_profiler_env_musl.sh
- scripts/bcc_helpers_build.sh
- scripts/build_aarch64_container.sh
- scripts/build_aarch64_executable.sh
- scripts/build_x86_64_container.sh
- scripts/build_x86_64_executable.sh
- scripts/cmp_tags.sh
- scripts/copy_resources_from_image.sh
- scripts/libunwind_build.sh
- scripts/list_needed_libs.sh
- scripts/perf_build.sh
- scripts/phpspy_build.sh
- scripts/prepare_machine-unknown-linux-musl.sh
- scripts/pyperf_build.sh
- scripts/pyspy_build.sh
- scripts/rbspy_build.sh
- scripts/verify_tag.sh
- shell_lint.sh
~~Let's see how many failures we have.~~ not too many, all set
Closes: #479
> Add shellcheck in CI

- gprofiler/profilers/__init__.py
Import only supported profilers on Windows
Conditionally import windows supported profilers
[See PR](https://github.com/Granulate/gprofiler/pull/442)
> Import windows specific profilers only

- gprofiler/profilers/dotnet.py
> dotnet timeout adjustment

- README.md
Closes: https://github.com/Granulate/gprofiler/issues/548
> docs: Document our collapsed format

- gprofiler/client.py
- gprofiler/main.py
- gprofiler/merge.py
This value is not used by the backend.
> Remove total_samples

- deploy/dataproc/gprofiler_initialization_action.sh
- deploy/systemd/create_systemd_service.sh
- gprofiler/profilers/node.py
- lint.sh
- shell_lint.sh
- tests/test.sh
> ci: Fix black not failing the CI & shellcheck all shell files

- gprofiler/profilers/node.py
https://github.com/Granulate/gprofiler/issues/560
> Add logging for changing DSO state and creating debugger socket

- gprofiler/profilers/node.py
This PR adds protection from exceptions with regards to closing debugger socket.
https://github.com/Granulate/gprofiler/issues/576
> Use with statement when creating Node.js debugger socket

- gprofiler/profilers/node.py
- gprofiler/profilers/perf.py
https://github.com/Granulate/gprofiler/issues/537
> nodejs: Fix removing file that doesn't exist

- gprofiler/profilers/node.py
- gprofiler/utils/__init__.py
Post https://github.com/Granulate/granulate-utils/pull/97
> Remove passthrough_exception parameter in run_in_ns()

- gprofiler/metadata/application_identifiers.py
- gprofiler/profilers/perf.py
- tests/conftest.py
- tests/test_appids.py
https://github.com/Granulate/gprofiler/issues/504
> nodejs: Implement getting appid

- gprofiler/profilers/node.py
(https://github.com/Granulate/gprofiler/issues/592)
Run fibonacci application in container with: docker run --user 5555:0, and then run gprofiler as exe.
> nodejs: Fix problem with permissions

- gprofiler/metadata/application_identifiers.py
- gprofiler/profilers/ruby.py
- tests/conftest.py
- tests/test_appids.py
https://github.com/Granulate/gprofiler/issues/505
> ruby: Implement getting appid

- Dockerfile
- pyi.Dockerfile
- scripts/build_x86_64_executable.sh
This PR fixes problem with building gProfiler on aarch64 architecture.
> Fix aarch64 centos image issue

- tests/test_sanity.py
See https://github.com/Granulate/gprofiler/issues/630.
> tests: php: Skip php tests that target host process

- scripts/async_profiler_build_shared.sh
Includes the fix https://github.com/jvm-profiling-tools/async-profiler/commit/ebda293a42c7db0b5918b0ef07ac6546958c764a.
> java: Upgrade async-profiler to v2.9g4

- gprofiler/metadata/application_metadata.py
- gprofiler/profilers/profiler_base.py
* Don't fail if getting exe/execfn fails
* Handle ZombieProcess errors gracefully
The trigger for this was some system where we're able to profile Java processes, but unable to read execfns (unable to access processes' `/proc/pid/mem`).
```
[2023-01-11 16:40:12,511] ERROR: gprofiler.metadata.application_metadata: Exception while collecting metadata in JavaMetadata!
File "granulate_utils/linux/process.py", line 106, in _translate_errors
File "granulate_utils/linux/process.py", line 98, in _read_process_memory
PermissionError: [Errno 13] Permission denied: '/proc/620/mem'
During handling of the above exception, another exception occurred:
File "gprofiler/metadata/application_metadata.py", line 52, in get_metadata
File …
```
> Improve app metadata robustness

- gprofiler/main.py
- gprofiler/spark/spark_collector.py
This PR enables running spark_metrics_collector in non-continuous mode
> Enable to run spark metrics collector in single collect mode [sparky branch]

- scripts/check_pyinstaller.sh
Print the errors from pyinstaller when it fails.
> Print pyinstaller errors

- gprofiler/profilers/perf.py
Robustness improvement. If those files are leaked due to "perf inject" / "perf script" unexpectedly failing/being killed, then this disk space is not freed.
> perf: Remove perf.data & perf.inject intermediates output also when "perf inject/script" fail

- gprofiler/spark/spark_collector.py
If we didn't find the RM/Master address upon launch, retry every cycle until we do.
Ran an EMR cluster with the bootstrap action. Verified data is reported.
> spark: Retry finding master address

- .github/workflows/build-on-windows.yml
- scripts/windows/build-pyspy.bat
- scripts/windows/build.bat
> Windows CI

- tests/test_app_metadata.py
- tests/test_executable.py
- tests/test_sanity.py
See https://github.com/Granulate/gprofiler/issues/697
> tests: dotnet: xfail test_executable_not_privileged

- gprofiler/__init__.py
After https://github.com/Granulate/gprofiler/pull/698
> gProfiler 1.20.0

- gprofiler/spark/spark_collector.py
time.monotonic does not represent current time.
> metrics: Fix timestamp

- gprofiler/main.py
- gprofiler/spark/collector.py
- gprofiler/spark/mode.py
- gprofiler/spark/sampler.py
Later we will isolate the sampler to be independent of Spark entirely.
> metrics: Move SparkSampler to separate module

- gprofiler/spark/sampler.py
> Spark metrics: Discovery interval changed to 5 seconds

- gprofiler/profilers/perf.py
- tests/test_perf.py
https://github.com/Granulate/gprofiler/issues/798
> Ignore unknown frames in perf get_average_frame_count()

- gprofiler/metadata/versions.py
- gprofiler/profilers/java.py
This PR converts CalledProcessError during java profiling and FileNotFoundError during ruby profiling to NoSuchProcess exception. 
https://github.com/Granulate/gprofiler/issues/797
> Gracefully handle various errors as NoSuchProcess

- tests/test.sh
- tests/test_app_metadata.py
- tests/test_sanity.py
There were more tweaks than ruby name change, but it turned out to be caused by my setup :)
> test installation tweak on aarch64

- README.md
- gprofiler/main.py
> Support refactored DBXWebUIEnvWrapper (old DatabricksClient)

- deploy/ecs/gprofiler_task_definition.json
Impose hard limits for memory and cpu in gprofiler ECS task definition
> ECS: Impose hard limits for memory and cpu

- gprofiler/metadata/application_identifiers.py
- tests/test_appids.py
Works properly, not sure about the naming convention though.
https://github.com/Granulate/gprofiler/issues/704
> gunicorn appid improvement

- gprofiler/metadata/application_identifiers.py
- tests/test_appids.py
https://github.com/Granulate/gprofiler/issues/693
> uvicorn appid improvement

- gprofiler/profilers/perf.py
- tests/containers/python/libpython.Dockerfile
https://github.com/Granulate/gprofiler/issues/824
> node exception leaks

- README.md
- gprofiler/main.py
- gprofiler/metadata/metadata_collector.py
Automatically disable pidns check and perf when running on Fargate.
> main: disable pid ns check and disable perf when running on Fargate

- gprofiler/metadata/application_metadata.py
- tests/test_app_metadata.py
Needs https://github.com/Granulate/granulate-utils/pull/182 and https://github.com/Granulate/granulate-utils/pull/180
> Add ELF arch as app metadata

- gprofiler/metadata/application_metadata.py
We really do need Aarch64 tests in the CI 😅
> Fix arch metadata with Aarch64

- scripts/prepare_machine-unknown-linux-musl.sh
1.2.13 is deleted from zlib.net
> build: Upgrade zlib to 1.3

- gprofiler/log.py
Main updates:
1. Breaking change in gLogger SDK (Need to pass `AuthToken`
2. Add support for CRIv1 grpc
3. Fixes to resolve_proc_root_links
> Update granulate-utils (CRI v1, resolve_proc_root_links fix, ...)

- dev-requirements.txt
- requirements.txt
For https://github.com/Granulate/gprofiler/security/dependabot/2
> Upgrade requests~=2.31.0 and docker~=7.0.0

- tests/conftest.py
- tests/test_java.py
> tests: java: Add test_sanity_latest_jvms

- gprofiler/profilers/java.py
> java: update minimal supported version on major 21

- gprofiler/__init__.py
> gProfiler 1.45.0

- gprofiler/profilers/perf.py
- gprofiler/utils/perf.py
- tests/test_perf.py
> utils/perf.py: copy `_parse_perf_script` and `_collapse_stack` from `profilers/perf.py`

- scripts/perf_build.sh
> Perf: fix `v6.7` build on aarch64

- gprofiler/__init__.py
> gProfiler 1.46.0

- gprofiler/profilers/java.py
> Profilers/java.py: add version 18 to minimal support 

- gprofiler/profilers/java.py
> profilers/java.py: new build minimal of version 21

- gprofiler/__init__.py
> gProfiler version 1.48.0

- gprofiler/profilers/python_ebpf.py
> gprofiler/python_ebpf.py: non-blocking standard output streams reading

- gprofiler/main.py
> Exposing gProfilers' `--heartbeat-file` flag

- gprofiler/__init__.py
> gProfiler version 1.49.0

- executable.Dockerfile
- scripts/fix_centos7.sh
> CI: centos 7 fix

- README.md
- gprofiler/main.py
- requirements.txt
> Deprecate --databricks-job-name-as-service-name

- gprofiler/__init__.py
> bump version to 1.50.0

- gprofiler/__init__.py
> gProfiler 1.51.0

- README.md
- gprofiler/__init__.py
Added documentation for rootless feature in README.md and iterated version for release
https://github.com/intel/gprofiler/issues/905
This is documentation for #936 
No tests necessary as this PR as there are no functional changes. Test for rootless feature TBD in subsequent PR.
> Added documentation for rootless feature in README.md and iterated version

- gprofiler/__init__.py
Update version to distinguish commits
> Update version to distinguish commits

- .github/workflows/build-test-deploy.yml
- scripts/setup_runner_requirements.sh
Make aarch build to run on all PRs
> Make aarch build to run on all PRs

- README.md
> Remove granulate.io links due to service shutdown

- gprofiler/hw_metrics.py
> Fix Bandit issue B404

- .github/workflows/codeql.yml
Enable static code analysis scans using Code QL.
Static code analysis is required in order to satisfy Intel's requirements.
Check if workflow succeeds with this branch.
> Create codeql.yml for SDL

- .github/workflows/build-on-windows.yml
- .github/workflows/build-test-deploy.yml
- .github/workflows/codeql.yml
- .github/workflows/linters.yml
Add permission blocks to workflow files, granting workflows only necessary permissions.
Scan findings # 2-11 here: https://github.com/intel/gprofiler/security/code-scanning?query=is%3Aopen+branch%3Amaster
Mitigates security vulnerabilities.
> Add missing security permissions to workflows (recreated PR)

- gprofiler/resources/flamegraph/flamegraph_template.html
Add an integrity check to a script import from a CDN which supports integrity checks.
https://github.com/intel/gprofiler/security/code-scanning/12
Improve app security.
> Mitigate inclusion of functionality from an untrusted source

- requirements.txt
> bump requests from 2.32.3 to 2.32.4

- gprofiler/main.py
> Fixes #977 gprofiler does not work on aarch64
